global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 @v2rayconfigamir 6547","type":"vless","server":"93.123.39.218","port":443,"uuid":"3130fccb-e72e-468d-b2ce-0721bb3058c8","udp":true,"tls":true,"network":"tcp","servername":"www.apple.com"}
  - {"name":"2 @v2rayconfigamir 6637","type":"vless","server":"5.178.110.202","port":2053,"uuid":"6202b230-417c-4d8e-b624-0f71afa9c75d","udp":true,"tls":true,"network":"ws","servername":"sni.111000.dynv6.net"}
  - {"name":"3 🔰 @PewezaVPN (تلگرام)socks://YmVpdGVuMzkzOjEyMw@2.180.23.229:3030#🔰 @PewezaVPN (تلگرام)","type":"vless","server":"94.101.179.197","port":443,"uuid":"788d2a40-12fe-4296-b802-d218308e769b","udp":true,"tls":true,"network":"tcp","servername":"archive-azd1101.telewebion.ir"}
  - {"name":"4 🔰 @PewezaVPN (تلگرام)","type":"vless","server":"65.21.145.122","port":30448,"uuid":"bb89519d-d352-466e-a223-ad7bf282fb4f","udp":true,"tls":false,"network":"tcp"}
  - {"name":"5 ⚡Telegram = @prrofile_purple","type":"vless","server":"broad-sky-9360.k7uztejf9ief.workers.dev","port":443,"uuid":"bf710ad2-4a43-4379-aa73-e684f00b6240","udp":true,"tls":true,"network":"ws","servername":"broad-sky-9360.k7uztejf9ief.workers.dev"}
  - {"name":"6 @v2rayconfigamir 1662","type":"vless","server":"193.109.120.119","port":443,"uuid":"fd37be2f-f8d1-47de-97e8-13c28107d31e","udp":true,"tls":true,"network":"tcp","servername":"est15.frostbot.ru"}
  - {"name":"7 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"172.67.191.189","port":443,"password":"OVsFRZT5jG","udp":true,"tls":true}
  - {"name":"8 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"45.85.118.88","port":2053,"password":"ZJU29smXwp","udp":true,"tls":true}
  - {"name":"9 🔰 @PewezaVPN (تلگرام)","type":"trojan","server":"185.143.235.5","port":443,"password":"biS(YrwB,3L$","udp":true,"tls":true}
  - {"name":"10 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"www.gossipglove.com","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"11 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"www.host-tracker.com","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"12 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"54.37.18.204","port":443,"password":"opentunnel.net-english30day","udp":true,"tls":true}
  - {"name":"13 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"15.204.9.172","port":443,"password":"opentunnel.net-usa30day","udp":true,"tls":true}
  - {"name":"14 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"13.36.80.221","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"15 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"13.37.186.179","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"16 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو","type":"trojan","server":"13.38.195.57","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"17 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"15.224.128.206","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"18 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"18.159.140.89","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"19 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"18.194.226.217","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"20 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو","type":"trojan","server":"3.120.169.133","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"21 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو","type":"trojan","server":"3.69.114.26","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"22 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"35.181.241.230","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"23 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"13.36.80.221","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"24 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"13.37.186.179","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"25 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"13.38.195.57","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"26 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"15.224.128.206","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"27 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"18.159.140.89","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"28 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"18.194.226.217","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"29 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"3.120.169.133","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"30 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"3.69.114.26","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"31 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"35.181.241.230","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"32 🍓@xixv2ray","type":"vmess","server":"cip.1iii1.de","port":443,"uuid":"83df5028-1637-4760-858e-bbacaab4b9b1","alterId":0,"cipher":"auto","udp":true}
  - {"name":"33 @v2rayconfigamir 1049","type":"vmess","server":"kklo.1xq.indevs.in","port":80,"uuid":"4e45c1b4-9107-45dd-9995-cdf7cbb44d9d","alterId":0,"cipher":"auto","udp":true}
  - {"name":"34 @v2rayconfigamir 1115","type":"vmess","server":"nqzkb.cmvvb.online","port":443,"uuid":"16604b48-7497-428c-a6d4-b017b3a30ce4","alterId":0,"cipher":"auto","udp":true}
  - {"name":"35 @v2rayconfigamir 7927","type":"vmess","server":"85.90.217.42","port":22324,"uuid":"04621bae-ab36-11ec-b909-0242ac120002","alterId":0,"cipher":"auto","udp":true}
  - {"name":"36 @v2rayconfigamir 6914","type":"vmess","server":"159.89.29.136","port":80,"uuid":"d20d6ede-433c-11ed-b81f-cfd905df9958","alterId":0,"cipher":"auto","udp":true}
  - {"name":"37 🔰 @PewezaVPN (تلگرام)","type":"vmess","server":"185.181.183.124","port":28094,"uuid":"a6440729-1046-4a9c-bc19-7c0ede4bf4d4","alterId":0,"cipher":"auto","udp":true}
  - {"name":"38 🔰 @PewezaVPN (تلگرام)","type":"vmess","server":"gsmvpn.gsmvx.com","port":5006,"uuid":"ef6e8954-20af-4266-a393-cccffa9db7c4","alterId":0,"cipher":"auto","udp":true}
  - {"name":"39 @v2rayconfigamir 7714","type":"vmess","server":"mghnnbj.1yy.ccwu.cc","port":80,"uuid":"4e45c1b4-9107-45dd-9995-cdf7cbb44d9d","alterId":0,"cipher":"auto","udp":true}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 @v2rayconfigamir 6547"
      - "2 @v2rayconfigamir 6637"
      - "3 🔰 @PewezaVPN (تلگرام)socks://YmVpdGVuMzkzOjEyMw@2.180.23.229:3030#🔰 @PewezaVPN (تلگرام)"
      - "4 🔰 @PewezaVPN (تلگرام)"
      - "5 ⚡Telegram = @prrofile_purple"
      - "6 @v2rayconfigamir 1662"
      - "7 ⚡Telegram = @SOSkeyNET"
      - "8 ⚡Telegram = @SOSkeyNET"
      - "9 🔰 @PewezaVPN (تلگرام)"
      - "10 ⚡Telegram = @SOSkeyNET"
      - "11 ⚡Telegram = @SOSkeyNET"
      - "12 ⚡Telegram = @SOSkeyNET"
      - "13 ⚡Telegram = @SOSkeyNET"
      - "14 ⚡Telegram = @SOSkeyNET"
      - "15 ⚡Telegram = @SOSkeyNET"
      - "16 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو"
      - "17 ⚡Telegram = @SOSkeyNET"
      - "18 ⚡Telegram = @SOSkeyNET"
      - "19 ⚡Telegram = @SOSkeyNET"
      - "20 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو"
      - "21 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو"
      - "22 ⚡Telegram = @SOSkeyNET"
      - "23 ⚡Telegram = @SOSkeyNET"
      - "24 ⚡Telegram = @SOSkeyNET"
      - "25 ⚡Telegram = @SOSkeyNET"
      - "26 ⚡Telegram = @SOSkeyNET"
      - "27 ⚡Telegram = @SOSkeyNET"
      - "28 ⚡Telegram = @SOSkeyNET"
      - "29 ⚡Telegram = @SOSkeyNET"
      - "30 ⚡Telegram = @SOSkeyNET"
      - "31 ⚡Telegram = @SOSkeyNET"
      - "32 🍓@xixv2ray"
      - "33 @v2rayconfigamir 1049"
      - "34 @v2rayconfigamir 1115"
      - "35 @v2rayconfigamir 7927"
      - "36 @v2rayconfigamir 6914"
      - "37 🔰 @PewezaVPN (تلگرام)"
      - "38 🔰 @PewezaVPN (تلگرام)"
      - "39 @v2rayconfigamir 7714"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 @v2rayconfigamir 6547"
      - "2 @v2rayconfigamir 6637"
      - "3 🔰 @PewezaVPN (تلگرام)socks://YmVpdGVuMzkzOjEyMw@2.180.23.229:3030#🔰 @PewezaVPN (تلگرام)"
      - "4 🔰 @PewezaVPN (تلگرام)"
      - "5 ⚡Telegram = @prrofile_purple"
      - "6 @v2rayconfigamir 1662"
      - "7 ⚡Telegram = @SOSkeyNET"
      - "8 ⚡Telegram = @SOSkeyNET"
      - "9 🔰 @PewezaVPN (تلگرام)"
      - "10 ⚡Telegram = @SOSkeyNET"
      - "11 ⚡Telegram = @SOSkeyNET"
      - "12 ⚡Telegram = @SOSkeyNET"
      - "13 ⚡Telegram = @SOSkeyNET"
      - "14 ⚡Telegram = @SOSkeyNET"
      - "15 ⚡Telegram = @SOSkeyNET"
      - "16 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو"
      - "17 ⚡Telegram = @SOSkeyNET"
      - "18 ⚡Telegram = @SOSkeyNET"
      - "19 ⚡Telegram = @SOSkeyNET"
      - "20 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو"
      - "21 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو"
      - "22 ⚡Telegram = @SOSkeyNET"
      - "23 ⚡Telegram = @SOSkeyNET"
      - "24 ⚡Telegram = @SOSkeyNET"
      - "25 ⚡Telegram = @SOSkeyNET"
      - "26 ⚡Telegram = @SOSkeyNET"
      - "27 ⚡Telegram = @SOSkeyNET"
      - "28 ⚡Telegram = @SOSkeyNET"
      - "29 ⚡Telegram = @SOSkeyNET"
      - "30 ⚡Telegram = @SOSkeyNET"
      - "31 ⚡Telegram = @SOSkeyNET"
      - "32 🍓@xixv2ray"
      - "33 @v2rayconfigamir 1049"
      - "34 @v2rayconfigamir 1115"
      - "35 @v2rayconfigamir 7927"
      - "36 @v2rayconfigamir 6914"
      - "37 🔰 @PewezaVPN (تلگرام)"
      - "38 🔰 @PewezaVPN (تلگرام)"
      - "39 @v2rayconfigamir 7714"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
