global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
proxies:
  - {"name":"27-🔄 LATEST-UPDATE 📅 SAT-09-ESFAND-1404 🕑 08:17","type":"vless","server":"127.0.0.1","port":1080,"uuid":"aaccbba-aacb-baac-abdc-aabccacabcbb","udp":true,"tls":true,"network":"tcp"}
  - {"name":"27-👨🏻‍💻 DEVELOPED-BY SOROUSH-MIRZAEI 📌 FOLLOW-CONTACT SYDSRSMRZ","type":"vless","server":"127.0.0.1","port":8080,"uuid":"aaaccbb-baca-baca-bcad-aacbabcbcbca","udp":true,"tls":true,"network":"tcp"}
proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "Auto"
      - "DIRECT"
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - "27-🔄 LATEST-UPDATE 📅 SAT-09-ESFAND-1404 🕑 08:17"
      - "27-👨🏻‍💻 DEVELOPED-BY SOROUSH-MIRZAEI 📌 FOLLOW-CONTACT SYDSRSMRZ"
rules:
  - GEOIP,IR,DIRECT
  - MATCH,Proxy
