global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 ⚡Telegram = @SOSkeyNET","type":"hysteria2","server":"181.214.99.162","port":35000,"password":"b4bd0613-ff7c-4f2f-954d-185915e6ddad"}
  - {"name":"2 @Capoit@Capoit","type":"vless","server":"finland.dehnavy.ir","port":39461,"uuid":"0195d3b8-8bfa-4c6e-9988-56396952a50a","udp":true,"tls":false,"network":"ws"}
  - {"name":"3 NetAccount","type":"vless","server":"g2-tun-nl.a1mshop2.xyz","port":22560,"uuid":"2947df46-35db-43cf-a3c2-b5aee2489504","udp":true,"tls":false,"network":"tcp"}
  - {"name":"4 @v2rayconfigamir 7046","type":"vless","server":"77.91.74.179","port":8443,"uuid":"309fa273-6579-4cb2-9143-7cad50401eba","udp":true,"tls":true,"network":"tcp","servername":"www.cloudflare.com"}
  - {"name":"5 🔰 @PewezaVPN (تلگرام)","type":"vless","server":"146.70.106.79","port":21252,"uuid":"3361a952-096a-4ea5-965b-556e2f870bba","udp":true,"tls":false,"network":"tcp"}
  - {"name":"6 @meliproxyy","type":"vless","server":"connected3.starpo3.ir","port":8080,"uuid":"3445138a-d30d-4b7b-ba80-0875c3b60d41","udp":true,"tls":false,"network":"tcp"}
  - {"name":"7 @Capoit","type":"vless","server":"109.95.67.200","port":25443,"uuid":"424b84b4-cd57-42eb-b1e0-5b618ffcb822","udp":true,"tls":false,"network":"tcp"}
  - {"name":"8 برای اتصال دائمی جوین شو🗾 prrofile_purple@","type":"vless","server":"81.90.29.39","port":2443,"uuid":"44dc6ac1-6126-4627-b889-9792a8188012","udp":true,"tls":true,"network":"grpc","servername":"academy.nvidia.com"}
  - {"name":"9 🔰 @PewezaVPN (تلگرام)","type":"vless","server":"g2-tun-nl.a1mshop2.xyz","port":22560,"uuid":"4a250ab6-d97f-4a6c-93d2-d9b2d6807b6d","udp":true,"tls":false,"network":"tcp"}
  - {"name":"10 🔰 @PewezaVPN (تلگرام)","type":"vless","server":"109.95.65.242","port":900,"uuid":"4dd14167-ddce-49d1-8322-133e82c0cbfb","udp":true,"tls":false,"network":"tcp"}
  - {"name":"11 🔰 @PewezaVPN (تلگرام)","type":"vless","server":"farzandeiran.iransalar.top","port":21531,"uuid":"5cc82fdd-847a-4b11-9f91-3d8f35ff9e09","udp":true,"tls":false,"network":"tcp"}
  - {"name":"12 proxymelimon","type":"vless","server":"188.244.122.138","port":2096,"uuid":"6202b230-417c-4d8e-b624-0f71afa9c75d","udp":true,"tls":true,"network":"ws","servername":"sni.111000.indevs.in"}
  - {"name":"13 hp-1","type":"vless","server":"mail.tomandjery.eu","port":1001,"uuid":"6a3ad064-be7c-40be-9a48-171885a359b7","udp":true,"tls":true,"network":"tcp","servername":"play.google.com"}
  - {"name":"14 dlc-new1.persianpinggame.com","type":"vless","server":"dlc-new1.persianpinggame.com","port":5101,"uuid":"7140445d-1bf6-11f1-9350-92000723b4ab","udp":true,"tls":false,"network":"tcp"}
  - {"name":"15 @Capoit@Capoit","type":"vless","server":"94.184.20.220","port":58290,"uuid":"7443fd1c-d867-71cb-ac5f-736eb09ba2b0","udp":true,"tls":false,"network":"tcp"}
  - {"name":"16 @v2rayconfigamir 2504","type":"vless","server":"192.9.162.122","port":1443,"uuid":"7a169e43-ff85-4572-9843-ba7207d07319","udp":true,"tls":true,"network":"tcp","servername":"swdist.apple.com"}
  - {"name":"17 🔰 @PewezaVPN (تلگرام)","type":"vless","server":"213.177.176.182","port":26401,"uuid":"8620a004-648c-43ab-9efe-4d3d82b12dc4","udp":true,"tls":false,"network":"tcp"}
  - {"name":"18 @MARAMBASHI 💙","type":"vless","server":"www.tomandjery.eu","port":1003,"uuid":"9208edb9-83c9-433f-bc56-90ffa33800e8","udp":true,"tls":true,"network":"tcp","servername":"play.google.com"}
  - {"name":"19 @Capoit@Capoit","type":"vless","server":"mail.tomandjery.eu","port":1001,"uuid":"9f4fa241-2576-40f3-ac95-8fb8400cf3ca","udp":true,"tls":true,"network":"tcp","servername":"play.google.com"}
  - {"name":"20 @Capoit@Capoit","type":"vless","server":"sr-d-2.sedarchahar.top","port":9102,"uuid":"a4f7ac23-8146-464b-a932-9753f97303aa","udp":true,"tls":false,"network":"tcp"}
  - {"name":"21 @Capoit@Capoit","type":"vless","server":"193.151.151.211","port":42595,"uuid":"c227aacf-30e7-48d1-9e98-99d78b8347e8","udp":true,"tls":false,"network":"tcp"}
  - {"name":"22 🔰 @PewezaVPN (تلگرام)","type":"vless","server":"v2.royalway.shop","port":2053,"uuid":"c3a8f526-6f41-4884-adb8-f33b4ec30fa6","udp":true,"tls":false,"network":"tcp"}
  - {"name":"23 @MARAMBASHI 💙","type":"vless","server":"platform.snapp.ir.green-gaming-company.ir","port":1011,"uuid":"c72511d7-1729-403d-92c5-7448533a369a","udp":true,"tls":false,"network":"tcp"}
  - {"name":"24 hhp","type":"vless","server":"ja3.diiginet.ir","port":1500,"uuid":"c8c75018-26ab-4501-be3e-f7bb33ed8c57","udp":true,"tls":false,"network":"tcp"}
  - {"name":"25 @MARAMBASHI 💙","type":"vless","server":"185.126.203.167","port":16957,"uuid":"c967de89-af86-4eba-be64-34e5656ca994","udp":true,"tls":false,"network":"tcp"}
  - {"name":"26 @Capoit","type":"vless","server":"l-iq-emergency2-7788yo.j0je.ir","port":5480,"uuid":"d40e96b2-0203-4e62-bffb-cc8f338917dd","udp":true,"tls":false,"network":"tcp"}
  - {"name":"27 @Capoit","type":"vless","server":"vipde5.persianpinggame.com","port":9093,"uuid":"e2fed65e-1ae0-11f1-8359-92000723b4ab","udp":true,"tls":false,"network":"tcp"}
  - {"name":"28 hp-3","type":"vless","server":"emergency5380.carpet-carpet-carped.ir","port":5380,"uuid":"ef2588ed-6162-4ee3-a002-39ef1c09e848","udp":true,"tls":false,"network":"tcp"}
  - {"name":"29 @Capoit@Capoit","type":"vless","server":"emg3.saipasamandemg3.sbs","port":2003,"uuid":"f75305e2-de53-4add-acc8-f9308394f5a4","udp":true,"tls":false,"network":"tcp"}
  - {"name":"30 @v2rayconfigamir 1237","type":"ss","server":"154.205.148.202","port":11202,"cipher":"chacha20-ietf-poly1305","password":"71807718f593d3e6"}
  - {"name":"31 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"chat.openai.com","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"32 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"www.multiplydose.com","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"33 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"54.37.18.204","port":443,"password":"opentunnel.net-english30day","udp":true,"tls":true}
  - {"name":"34 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"15.204.9.172","port":443,"password":"opentunnel.net-usa30day","udp":true,"tls":true}
  - {"name":"35 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"15.188.96.111","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"36 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو","type":"trojan","server":"3.127.171.45","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"37 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"51.44.98.27","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"38 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"63.183.124.201","port":22223,"password":"telegram-id-directvpn","udp":true,"tls":true}
  - {"name":"39 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"15.188.96.111","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"40 (S101)🇩🇪t.me/PrivateVPNs","type":"trojan","server":"3.127.171.45","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"41 (S103)🇨🇵t.me/PrivateVPNs","type":"trojan","server":"51.44.98.27","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"42 ⚡Telegram = @SOSkeyNET","type":"trojan","server":"63.183.124.201","port":22222,"password":"telegram-id-privatevpns","udp":true,"tls":true}
  - {"name":"43 NetAccount","type":"vmess","server":"cip.1iii1.de","port":443,"uuid":"83df5028-1637-4760-858e-bbacaab4b9b1","alterId":0,"cipher":"auto","udp":true}
  - {"name":"44 @v2rayconfigamir 4563","type":"vmess","server":"45.15.185.17","port":80,"uuid":"c503a96a-a2f5-4847-a31f-20c17ecf3be4","alterId":0,"cipher":"auto","udp":true}
  - {"name":"45 @v2rayconfigamir 7010","type":"vmess","server":"45.89.52.207","port":39651,"uuid":"ac4c12c5-45f2-4398-a718-9983941ede2b","alterId":0,"cipher":"auto","udp":true}
  - {"name":"46 ⚡️Telegram = @SOSkeyNET","type":"vmess","server":"109.122.240.89","port":6533,"uuid":"86857427-d4ff-4752-a066-49c01d864615","alterId":0,"cipher":"auto","udp":true}
  - {"name":"47 ⚡️Telegram = @SOSkeyNET","type":"vmess","server":"us.zarasite.ir","port":6531,"uuid":"3f2d60fc-512d-4811-b50c-18013e32c162","alterId":0,"cipher":"auto","udp":true}
  - {"name":"48 @MARAMBASHI 💙","type":"vmess","server":"tun.p2p1.sbs","port":2020,"uuid":"497868e2-0b12-4244-a044-3ad0a94cb46b","alterId":0,"cipher":"auto","udp":true}
  - {"name":"49 @v2rayconfigamir 5155","type":"vmess","server":"mijuy.1x8.indevs.in","port":80,"uuid":"4e45c1b4-9107-45dd-9995-cdf7cbb44d9d","alterId":0,"cipher":"auto","udp":true}
  - {"name":"50 ⚡️Telegram = @SOSkeyNET","type":"vmess","server":"sv4.oxypingbot.in","port":19288,"uuid":"30acdd62-63e2-4391-87b8-8831217b874e","alterId":0,"cipher":"auto","udp":true}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 ⚡Telegram = @SOSkeyNET"
      - "2 @Capoit@Capoit"
      - "3 NetAccount"
      - "4 @v2rayconfigamir 7046"
      - "5 🔰 @PewezaVPN (تلگرام)"
      - "6 @meliproxyy"
      - "7 @Capoit"
      - "8 برای اتصال دائمی جوین شو🗾 prrofile_purple@"
      - "9 🔰 @PewezaVPN (تلگرام)"
      - "10 🔰 @PewezaVPN (تلگرام)"
      - "11 🔰 @PewezaVPN (تلگرام)"
      - "12 proxymelimon"
      - "13 hp-1"
      - "14 dlc-new1.persianpinggame.com"
      - "15 @Capoit@Capoit"
      - "16 @v2rayconfigamir 2504"
      - "17 🔰 @PewezaVPN (تلگرام)"
      - "18 @MARAMBASHI 💙"
      - "19 @Capoit@Capoit"
      - "20 @Capoit@Capoit"
      - "21 @Capoit@Capoit"
      - "22 🔰 @PewezaVPN (تلگرام)"
      - "23 @MARAMBASHI 💙"
      - "24 hhp"
      - "25 @MARAMBASHI 💙"
      - "26 @Capoit"
      - "27 @Capoit"
      - "28 hp-3"
      - "29 @Capoit@Capoit"
      - "30 @v2rayconfigamir 1237"
      - "31 ⚡Telegram = @SOSkeyNET"
      - "32 ⚡Telegram = @SOSkeyNET"
      - "33 ⚡Telegram = @SOSkeyNET"
      - "34 ⚡Telegram = @SOSkeyNET"
      - "35 ⚡Telegram = @SOSkeyNET"
      - "36 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو"
      - "37 ⚡Telegram = @SOSkeyNET"
      - "38 ⚡Telegram = @SOSkeyNET"
      - "39 ⚡Telegram = @SOSkeyNET"
      - "40 (S101)🇩🇪t.me/PrivateVPNs"
      - "41 (S103)🇨🇵t.me/PrivateVPNs"
      - "42 ⚡Telegram = @SOSkeyNET"
      - "43 NetAccount"
      - "44 @v2rayconfigamir 4563"
      - "45 @v2rayconfigamir 7010"
      - "46 ⚡️Telegram = @SOSkeyNET"
      - "47 ⚡️Telegram = @SOSkeyNET"
      - "48 @MARAMBASHI 💙"
      - "49 @v2rayconfigamir 5155"
      - "50 ⚡️Telegram = @SOSkeyNET"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 ⚡Telegram = @SOSkeyNET"
      - "2 @Capoit@Capoit"
      - "3 NetAccount"
      - "4 @v2rayconfigamir 7046"
      - "5 🔰 @PewezaVPN (تلگرام)"
      - "6 @meliproxyy"
      - "7 @Capoit"
      - "8 برای اتصال دائمی جوین شو🗾 prrofile_purple@"
      - "9 🔰 @PewezaVPN (تلگرام)"
      - "10 🔰 @PewezaVPN (تلگرام)"
      - "11 🔰 @PewezaVPN (تلگرام)"
      - "12 proxymelimon"
      - "13 hp-1"
      - "14 dlc-new1.persianpinggame.com"
      - "15 @Capoit@Capoit"
      - "16 @v2rayconfigamir 2504"
      - "17 🔰 @PewezaVPN (تلگرام)"
      - "18 @MARAMBASHI 💙"
      - "19 @Capoit@Capoit"
      - "20 @Capoit@Capoit"
      - "21 @Capoit@Capoit"
      - "22 🔰 @PewezaVPN (تلگرام)"
      - "23 @MARAMBASHI 💙"
      - "24 hhp"
      - "25 @MARAMBASHI 💙"
      - "26 @Capoit"
      - "27 @Capoit"
      - "28 hp-3"
      - "29 @Capoit@Capoit"
      - "30 @v2rayconfigamir 1237"
      - "31 ⚡Telegram = @SOSkeyNET"
      - "32 ⚡Telegram = @SOSkeyNET"
      - "33 ⚡Telegram = @SOSkeyNET"
      - "34 ⚡Telegram = @SOSkeyNET"
      - "35 ⚡Telegram = @SOSkeyNET"
      - "36 ⚡Telegram = @SOSkeyNET👈 آموزش اتصال 👉⚡️Telegram = @SOSkeyNET عضو شو"
      - "37 ⚡Telegram = @SOSkeyNET"
      - "38 ⚡Telegram = @SOSkeyNET"
      - "39 ⚡Telegram = @SOSkeyNET"
      - "40 (S101)🇩🇪t.me/PrivateVPNs"
      - "41 (S103)🇨🇵t.me/PrivateVPNs"
      - "42 ⚡Telegram = @SOSkeyNET"
      - "43 NetAccount"
      - "44 @v2rayconfigamir 4563"
      - "45 @v2rayconfigamir 7010"
      - "46 ⚡️Telegram = @SOSkeyNET"
      - "47 ⚡️Telegram = @SOSkeyNET"
      - "48 @MARAMBASHI 💙"
      - "49 @v2rayconfigamir 5155"
      - "50 ⚡️Telegram = @SOSkeyNET"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
