global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 🇧🇬 Bulgaria, Veliko Tarnovo | [BL]","type":"hysteria2","server":"s544.ccgfw.online","port":443,"password":"205d6869-02ca-3b36-b933-be2465250c7e"}
  - {"name":"2 🇫🇷 France, Paris | 🌐 | [BL]","type":"hysteria2","server":"62.210.10.107","port":64772,"password":"github.com/Alvin9999-newpac/fanqiang"}
  - {"name":"3 🇫🇷 France, Paris | 🌐 | [BL]","type":"hysteria2","server":"62.210.26.173","port":64772,"password":"github.com/Alvin9999-newpac/fanqiang"}
  - {"name":"4 🇷🇺 Russia | 🌐 | [BL]","type":"hysteria2","server":"195.133.53.33","port":443,"password":"10550754-cf62-3d3b-ba6a-50be27a275d7"}
  - {"name":"5 🇫🇮 Finland, Helsinki | 🌐 | [BL]","type":"vless","server":"bc-de-wc.ray-balance.space","port":4443,"uuid":"0eca1f22-e5a1-4888-a0fa-c2345e87cf2f","udp":true,"tls":false,"network":"grpc"}
  - {"name":"6 🇩🇪 Germany, Frankfurt am Main | [BL]","type":"vless","server":"78.17.147.65","port":443,"uuid":"b67ed271-5a34-4d07-9970-f8ba27ca2c8a","udp":true,"tls":true,"network":"tcp","servername":"www.microsoft.com"}
  - {"name":"7 🇩🇪 Germany, Frankfurt am Main | 🌐 | [BL]","type":"vless","server":"de2.unoix.co","port":31606,"uuid":"a0b7c251-a27c-410a-89a7-73a31e4e6af9","udp":true,"tls":true,"network":"tcp","servername":"www.yahoo.com"}
  - {"name":"8 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | [BL]","type":"vless","server":"82.27.2.239","port":18034,"uuid":"telegramchannel-probabblynot","udp":true,"tls":true,"network":"tcp","servername":"refersion.com"}
  - {"name":"9 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | [BL]","type":"vless","server":"probabblynot.fazelextremeisreal.com","port":18034,"uuid":"telegramchannel-probabblynot","udp":true,"tls":true,"network":"tcp","servername":"refersion.com"}
  - {"name":"10 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | 🌐 | [BL]","type":"vless","server":"194.58.41.158","port":44444,"uuid":"10484bee-8516-400a-9b1e-efb5144ad324","udp":true,"tls":true,"network":"xhttp","servername":"apple.com"}
  - {"name":"11 🇭🇰 Hong Kong, Hong Kong | 🌐 | [BL]","type":"vless","server":"hk01.jgpy.help","port":21002,"uuid":"a4521dcc-01fc-4d5d-bd23-1543c6f8c571","udp":true,"tls":true,"network":"tcp","servername":"apple.com"}
  - {"name":"12 🇭🇺 Hungary, Budapest | 🌐 | [BL]","type":"vless","server":"cdn7-09.vk-cdnvideo.com","port":8443,"uuid":"931729a8-3c20-4841-89a1-f18dc9ce0a6f","udp":true,"tls":true,"network":"tcp","servername":"cdn7-09.vk-cdnvideo.com"}
  - {"name":"13 🇰🇷 South Korea, Seoul | [BL]","type":"vless","server":"47.80.57.6","port":11101,"uuid":"e4e7866d-920b-4a53-a8e2-6ae9b2a42fc2","udp":true,"tls":false,"network":"tcp"}
  - {"name":"14 🇳🇱 The Netherlands, Amsterdam | [BL]","type":"vless","server":"89.124.69.82","port":1310,"uuid":"v2raydia","udp":true,"tls":false,"network":"ws"}
  - {"name":"15 🇳🇱 The Netherlands, Amsterdam (Westpoort) | 🌐 | [BL]","type":"vless","server":"45.67.136.114","port":7443,"uuid":"10484bee-8516-400a-9b1e-efb5144ad324","udp":true,"tls":true,"network":"tcp","servername":"stackoverflow.com"}
  - {"name":"16 🇳🇱 The Netherlands, Dronten | [BL]","type":"vless","server":"91.198.77.242","port":8443,"uuid":"3e809b21-e29b-49ec-a7fb-5301ec7c1cee","udp":true,"tls":false,"network":"ws"}
  - {"name":"17 🇳🇱 The Netherlands, Dronten | [BL]","type":"vless","server":"food.artmisserver.site","port":8443,"uuid":"3e809b21-e29b-49ec-a7fb-5301ec7c1cee","udp":true,"tls":false,"network":"ws"}
  - {"name":"18 🇹🇷 Turkey, Paşaköy | [BL]","type":"vless","server":"185.181.211.81","port":37141,"uuid":"71310f0a-1c4f-492d-8dec-fd755639d08a","udp":true,"tls":false,"network":"tcp"}
  - {"name":"19 🇬🇧 United Kingdom, London | [BL]","type":"vless","server":"s642.ccgfw.top","port":443,"uuid":"205d6869-02ca-3b36-b933-be2465250c7e","udp":true,"tls":true,"network":"tcp","servername":"u716087u4c78s642.ccgfw.top"}
  - {"name":"20 🇬🇧 United Kingdom, London | [BL]","type":"vless","server":"s643.ccgfw.top","port":443,"uuid":"205d6869-02ca-3b36-b933-be2465250c7e","udp":true,"tls":true,"network":"tcp","servername":"u716087u7190s643.ccgfw.top"}
  - {"name":"21 🇬🇧 United Kingdom, London | [BL]","type":"vless","server":"s644.ccgfw.top","port":443,"uuid":"205d6869-02ca-3b36-b933-be2465250c7e","udp":true,"tls":true,"network":"tcp","servername":"s644.ccgfw.top"}
  - {"name":"22 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]","type":"vless","server":"31.76.126.135","port":2040,"uuid":"17451fec-af94-4715-8c2f-7f6839130d0a","udp":true,"tls":true,"network":"tcp","servername":"tradingview.com"}
  - {"name":"23 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]","type":"vless","server":"31.76.126.141","port":2040,"uuid":"17451fec-af94-4715-8c2f-7f6839130d0a","udp":true,"tls":true,"network":"tcp","servername":"tradingview.com"}
  - {"name":"24 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]","type":"vless","server":"de02.lumixvpn.org","port":443,"uuid":"ed98e66d-5dbe-4b6d-9032-250e61eaf53f","udp":true,"tls":true,"network":"tcp","servername":"de02.lumixvpn.org"}
  - {"name":"25 🇺🇸 United States, Herndon | [BL]","type":"vless","server":"167.104.223.14","port":443,"uuid":"b67ed271-5a34-4d07-9970-f8ba27ca2c8a","udp":true,"tls":true,"network":"tcp","servername":"www.microsoft.com"}
  - {"name":"26 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]","type":"vless","server":"208.103.161.170","port":443,"uuid":"28f79470-c550-40b0-9e46-834a46ac8da8","udp":true,"tls":true,"network":"ws","servername":"help.viu.com.cyylr.eu.cc"}
  - {"name":"27 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]","type":"vless","server":"154.211.8.84","port":2083,"uuid":"40af9131-d540-448a-bc56-5bba147a1dc3","udp":true,"tls":true,"network":"ws","servername":"proxy-3us.pages.dev"}
  - {"name":"28 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]","type":"vless","server":"198.62.62.18","port":443,"uuid":"ace095c0-debd-46fd-903f-d29b9c8b4101","udp":true,"tls":true,"network":"ws","servername":"collection.linefriends.com.cyylr.eu.cc"}
  - {"name":"29 🌐 Anycast-IP | 🇨🇦 🇫🇮 🇮🇩 | [BL]","type":"vless","server":"208.103.161.170","port":443,"uuid":"2dc797c8-9588-48a6-bc4a-265c23d87cd6","udp":true,"tls":true,"network":"ws","servername":"ava.game.naver.com.cyylr.eu.cc"}
  - {"name":"30 🌐 Anycast-IP | 🇫🇮 | [BL]","type":"vless","server":"208.103.161.170","port":443,"uuid":"fc965ad9-bdd7-4815-ad71-b39ec5972dc1","udp":true,"tls":true,"network":"ws","servername":"octopusss4.com"}
  - {"name":"31 🌐 Anycast-IP | 🇬🇧 🇳🇱 | [BL]","type":"vless","server":"auto.datamove.online","port":2040,"uuid":"17451fec-af94-4715-8c2f-7f6839130d0a","udp":true,"tls":true,"network":"tcp","servername":"tradingview.com"}
  - {"name":"32 🌐 Anycast-IP | 🇵🇱 🇸🇪 | [BL]","type":"vless","server":"bc-pl-1c.ray-balance.space","port":4443,"uuid":"0eca1f22-e5a1-4888-a0fa-c2345e87cf2f","udp":true,"tls":false,"network":"grpc"}
  - {"name":"33 🇫🇷 France, Paris | [BL]","type":"trojan","server":"198.62.62.23","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"34 🇵🇱 Poland, Warsaw | [BL]","type":"trojan","server":"81.255.155.10","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"35 🇸🇬 Singapore, Singapore | 🌐 | [BL]","type":"trojan","server":"jpbgp.netvigor.cc","port":19128,"password":"gcuCpQfaiVeDBdWG","udp":true,"tls":true}
  - {"name":"36 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]","type":"trojan","server":"208.103.161.170","port":443,"password":"386bd471-4e29-4e79-9a3c-6bc6076ce4b6","udp":true,"tls":true}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 🇧🇬 Bulgaria, Veliko Tarnovo | [BL]"
      - "2 🇫🇷 France, Paris | 🌐 | [BL]"
      - "3 🇫🇷 France, Paris | 🌐 | [BL]"
      - "4 🇷🇺 Russia | 🌐 | [BL]"
      - "5 🇫🇮 Finland, Helsinki | 🌐 | [BL]"
      - "6 🇩🇪 Germany, Frankfurt am Main | [BL]"
      - "7 🇩🇪 Germany, Frankfurt am Main | 🌐 | [BL]"
      - "8 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | [BL]"
      - "9 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | [BL]"
      - "10 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | 🌐 | [BL]"
      - "11 🇭🇰 Hong Kong, Hong Kong | 🌐 | [BL]"
      - "12 🇭🇺 Hungary, Budapest | 🌐 | [BL]"
      - "13 🇰🇷 South Korea, Seoul | [BL]"
      - "14 🇳🇱 The Netherlands, Amsterdam | [BL]"
      - "15 🇳🇱 The Netherlands, Amsterdam (Westpoort) | 🌐 | [BL]"
      - "16 🇳🇱 The Netherlands, Dronten | [BL]"
      - "17 🇳🇱 The Netherlands, Dronten | [BL]"
      - "18 🇹🇷 Turkey, Paşaköy | [BL]"
      - "19 🇬🇧 United Kingdom, London | [BL]"
      - "20 🇬🇧 United Kingdom, London | [BL]"
      - "21 🇬🇧 United Kingdom, London | [BL]"
      - "22 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]"
      - "23 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]"
      - "24 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]"
      - "25 🇺🇸 United States, Herndon | [BL]"
      - "26 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]"
      - "27 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]"
      - "28 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]"
      - "29 🌐 Anycast-IP | 🇨🇦 🇫🇮 🇮🇩 | [BL]"
      - "30 🌐 Anycast-IP | 🇫🇮 | [BL]"
      - "31 🌐 Anycast-IP | 🇬🇧 🇳🇱 | [BL]"
      - "32 🌐 Anycast-IP | 🇵🇱 🇸🇪 | [BL]"
      - "33 🇫🇷 France, Paris | [BL]"
      - "34 🇵🇱 Poland, Warsaw | [BL]"
      - "35 🇸🇬 Singapore, Singapore | 🌐 | [BL]"
      - "36 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 🇧🇬 Bulgaria, Veliko Tarnovo | [BL]"
      - "2 🇫🇷 France, Paris | 🌐 | [BL]"
      - "3 🇫🇷 France, Paris | 🌐 | [BL]"
      - "4 🇷🇺 Russia | 🌐 | [BL]"
      - "5 🇫🇮 Finland, Helsinki | 🌐 | [BL]"
      - "6 🇩🇪 Germany, Frankfurt am Main | [BL]"
      - "7 🇩🇪 Germany, Frankfurt am Main | 🌐 | [BL]"
      - "8 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | [BL]"
      - "9 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | [BL]"
      - "10 🇩🇪 Germany, Frankfurt am Main (Innenstadt I) | 🌐 | [BL]"
      - "11 🇭🇰 Hong Kong, Hong Kong | 🌐 | [BL]"
      - "12 🇭🇺 Hungary, Budapest | 🌐 | [BL]"
      - "13 🇰🇷 South Korea, Seoul | [BL]"
      - "14 🇳🇱 The Netherlands, Amsterdam | [BL]"
      - "15 🇳🇱 The Netherlands, Amsterdam (Westpoort) | 🌐 | [BL]"
      - "16 🇳🇱 The Netherlands, Dronten | [BL]"
      - "17 🇳🇱 The Netherlands, Dronten | [BL]"
      - "18 🇹🇷 Turkey, Paşaköy | [BL]"
      - "19 🇬🇧 United Kingdom, London | [BL]"
      - "20 🇬🇧 United Kingdom, London | [BL]"
      - "21 🇬🇧 United Kingdom, London | [BL]"
      - "22 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]"
      - "23 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]"
      - "24 🇬🇧 United Kingdom, Martlesham (Martlesham Heath) | [BL]"
      - "25 🇺🇸 United States, Herndon | [BL]"
      - "26 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]"
      - "27 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]"
      - "28 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]"
      - "29 🌐 Anycast-IP | 🇨🇦 🇫🇮 🇮🇩 | [BL]"
      - "30 🌐 Anycast-IP | 🇫🇮 | [BL]"
      - "31 🌐 Anycast-IP | 🇬🇧 🇳🇱 | [BL]"
      - "32 🌐 Anycast-IP | 🇵🇱 🇸🇪 | [BL]"
      - "33 🇫🇷 France, Paris | [BL]"
      - "34 🇵🇱 Poland, Warsaw | [BL]"
      - "35 🇸🇬 Singapore, Singapore | 🌐 | [BL]"
      - "36 🌐 Anycast-IP | 🇨🇦 🇫🇮 | [BL]"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
