global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 🇨🇦 Canada, Toronto | 🌐 | [BL]","type":"hysteria2","server":"node.embrofree.org","port":443,"password":"4a6c225b-46a2-494d-a190-0b0a7c5205d4"}
  - {"name":"2 🇷🇴 🇷🇴 Romania, Bucharest | 🌐 | [BL]","type":"hysteria2","server":"185.156.44.99","port":443,"password":"gf1:gfhysteria2024"}
  - {"name":"3 🇸🇬 Singapore, Singapore | [BL]","type":"hysteria2","server":"vpn-sg-002.fastervpn.world","port":443,"password":"H7mP2xY9kJ4nQ9wR5tF6vB3z"}
  - {"name":"4 🇸🇬 🇸🇬 Singapore, Singapore | [BL]","type":"hysteria2","server":"43.156.90.144","port":34567,"password":"P6qkAwznuC076mbIR2cGPg=="}
  - {"name":"5 🇸🇬 🇸🇬 Singapore, Singapore | [BL]","type":"hysteria2","server":"13.212.75.123","port":443,"password":"qQe1z5kU8kN6SlKnDt9Ru3Qp"}
  - {"name":"6 🇸🇬 🇸🇬 Singapore, Singapore | [BL]","type":"hysteria2","server":"18.143.149.2","port":443,"password":"qQe1z5kU8kN6SlKnDt9Ru3Qp"}
  - {"name":"7 🇸🇬 🇸🇬 Singapore, Singapore (Loyang) | 🌐 | [BL]","type":"hysteria2","server":"138.2.73.238","port":50160,"password":"f87376e17da040ed04c9665ce8972930"}
  - {"name":"8 🇰🇷 🇰🇷 South Korea, Yangcheondong | [BL]","type":"hysteria2","server":"132.226.226.189","port":50160,"password":"1671a252e2a97dc2bda4e515475931da"}
  - {"name":"9 🇸🇪 Sweden, Stockholm | 🌐 | [BL]","type":"hysteria2","server":"swe.frkn.org","port":8443,"password":"3b8c82ed-fe66-472d-915e-034ccb57103f"}
  - {"name":"10 🇳🇱 The Netherlands, Amsterdam | [BL]","type":"hysteria2","server":"nl.vpn.legendaah.xyz","port":36723,"password":"Krab9Hyst2_Rk7pQ2xL"}
  - {"name":"11 🇺🇸 🇺🇸 United States | 🌐 | [BL]","type":"hysteria2","server":"155.117.19.221","port":30001,"password":"6fe3a600-4bcf-4040-81eb-ccd29231db2b"}
  - {"name":"12 🇺🇸 🇺🇸 United States, San Jose | 🌐 | [BL]","type":"hysteria2","server":"163.192.14.135","port":50160,"password":"099830134df5ac3a04a4b21d39b8c395"}
  - {"name":"13 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]","type":"vless","server":"lv01.tranzit-net.ru","port":443,"uuid":"618acefa-2ff1-41b0-a295-f8a08858a897","udp":true,"tls":true,"network":"tcp","servername":"d.tranzit-net.ru"}
  - {"name":"14 🇲🇩 Moldova, Chisinau | [BL]","type":"vless","server":"bul2.helper-internet.com","port":443,"uuid":"ae8e0f7d-b661-41ca-b55d-d8c383adb2f8","udp":true,"tls":true,"network":"tcp","servername":"bul2.helper-internet.com"}
  - {"name":"15 🇳🇴 🇳🇴 Norway, Sandefjord | [BL]","type":"vless","server":"151.242.168.237","port":443,"uuid":"19a368d5-41bf-4821-986c-ed84901f4f30","udp":true,"tls":true,"network":"tcp","servername":"frantax.my3cx.de"}
  - {"name":"16 🇺🇸 🇳🇱 The Netherlands, Schiphol-Rijk | [BL]","type":"vless","server":"69.46.46.64","port":443,"uuid":"5be592df-57bb-4e02-8662-01953687122d","udp":true,"tls":true,"network":"ws","servername":"javadiis-production.up.railway.app"}
  - {"name":"17 🇳🇱 The Netherlands, Schiphol-Rijk | [BL]","type":"vless","server":"javadiis-production.up.railway.app","port":443,"uuid":"5be592df-57bb-4e02-8662-01953687122d","udp":true,"tls":true,"network":"ws","servername":"javadiis-production.up.railway.app"}
  - {"name":"18 🇹🇷 Turkey, Istanbul | [BL]","type":"vless","server":"dda685345af09097dda685345af09097.drwrdoh.org","port":2025,"uuid":"65e294c6-9733-40cd-ade4-9bcf4017a1bd","udp":true,"tls":true,"network":"xhttp","servername":"amp-api-edge.apps.apple.com"}
  - {"name":"19 🇹🇷 Turkey, Istanbul | [BL]","type":"vless","server":"f43a79a4ff5a203af43a79a4ff5a203a.drwrdoh.org","port":2025,"uuid":"65e294c6-9733-40cd-ade4-9bcf4017a1bd","udp":true,"tls":true,"network":"xhttp","servername":"amp-api-edge.apps.apple.com"}
  - {"name":"20 🇹🇷 Turkey, Yakuplu | [BL]","type":"vless","server":"tr.privatevip.ir","port":2002,"uuid":"85b27fbd-33d6-4a3a-bf5b-c3cf97772893","udp":true,"tls":false,"network":"ws"}
  - {"name":"21 🇹🇷 Turkey, Yakuplu | [BL]","type":"vless","server":"tr.privatevip.ir","port":2500,"uuid":"85b27fbd-33d6-4a3a-bf5b-c3cf97772893","udp":true,"tls":false,"network":"ws"}
  - {"name":"22 🇬🇧 🇬🇧 United Kingdom, Maidenhead | [BL]","type":"vless","server":"109.169.84.72","port":443,"uuid":"7f437070-a14e-4355-bfbc-a6036a6bb040","udp":true,"tls":true,"network":"tcp","servername":"strapi.io"}
  - {"name":"23 🇱🇻 🌐 Anycast-IP | 🇨🇭 🇫🇮 🇸🇪 | [BL]","type":"vless","server":"185.145.245.144","port":443,"uuid":"618acefa-2ff1-41b0-a295-f8a08858a897","udp":true,"tls":true,"network":"tcp","servername":"d.tranzit-net.ru"}
  - {"name":"24 🌐 Anycast-IP | 🇨🇭 🇸🇪 | [BL]","type":"vless","server":"lv03.tranzit-net.ru","port":443,"uuid":"618acefa-2ff1-41b0-a295-f8a08858a897","udp":true,"tls":true,"network":"tcp","servername":"d.tranzit-net.ru"}
  - {"name":"25 🇺🇸 🌐 Anycast-IP | 🇬🇧 🇺🇸 | [BL]","type":"vless","server":"80.76.44.154","port":443,"uuid":"419f25c1-bc35-412e-93fb-258efee859b5","udp":true,"tls":true,"network":"tcp","servername":"nl6.murhost.network"}
  - {"name":"26 🇷🇺 🌐 Anycast-IP | 🇩🇪 🇷🇺 🇸🇨 | [BL]","type":"vless","server":"201.24.49.77","port":2200,"uuid":"af60d475-3c13-41cf-af0e-18353d08877a","udp":true,"tls":false,"network":"ws"}
  - {"name":"27 🇫🇷 🇫🇷 France, Lyon | [BL]","type":"trojan","server":"194.9.172.236","port":1105,"password":"kakashka13222","udp":true,"tls":true}
  - {"name":"28 🇯🇵 Japan, Shibuya City | [BL]","type":"trojan","server":"jp200m.jiasu.asia","port":50000,"password":"5259333f-7f21-47a1-80fa-2a0c23db8e4f","udp":true,"tls":true}
  - {"name":"29 🇯🇵 Japan, Shibuya City | [BL]","type":"trojan","server":"jp200m.jiasu.asia","port":50000,"password":"fd3f82cc-bf25-4d3a-a379-09834800ade9","udp":true,"tls":true}
  - {"name":"30 🇱🇻 Latvia, Riga | [BL]","type":"trojan","server":"lv01.botovod.space","port":510,"password":"8qCNZU2XdtefT7uB4uPxgRR839btqMG8","udp":true,"tls":true}
  - {"name":"31 🇹🇷 Turkey, Yakuplu | [BL]","type":"vmess","server":"tr.privatevip.ir","port":2503,"uuid":"85b27fbd-33d6-4a3a-bf5b-c3cf97772893","alterId":0,"cipher":"auto","udp":true}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 🇨🇦 Canada, Toronto | 🌐 | [BL]"
      - "2 🇷🇴 🇷🇴 Romania, Bucharest | 🌐 | [BL]"
      - "3 🇸🇬 Singapore, Singapore | [BL]"
      - "4 🇸🇬 🇸🇬 Singapore, Singapore | [BL]"
      - "5 🇸🇬 🇸🇬 Singapore, Singapore | [BL]"
      - "6 🇸🇬 🇸🇬 Singapore, Singapore | [BL]"
      - "7 🇸🇬 🇸🇬 Singapore, Singapore (Loyang) | 🌐 | [BL]"
      - "8 🇰🇷 🇰🇷 South Korea, Yangcheondong | [BL]"
      - "9 🇸🇪 Sweden, Stockholm | 🌐 | [BL]"
      - "10 🇳🇱 The Netherlands, Amsterdam | [BL]"
      - "11 🇺🇸 🇺🇸 United States | 🌐 | [BL]"
      - "12 🇺🇸 🇺🇸 United States, San Jose | 🌐 | [BL]"
      - "13 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]"
      - "14 🇲🇩 Moldova, Chisinau | [BL]"
      - "15 🇳🇴 🇳🇴 Norway, Sandefjord | [BL]"
      - "16 🇺🇸 🇳🇱 The Netherlands, Schiphol-Rijk | [BL]"
      - "17 🇳🇱 The Netherlands, Schiphol-Rijk | [BL]"
      - "18 🇹🇷 Turkey, Istanbul | [BL]"
      - "19 🇹🇷 Turkey, Istanbul | [BL]"
      - "20 🇹🇷 Turkey, Yakuplu | [BL]"
      - "21 🇹🇷 Turkey, Yakuplu | [BL]"
      - "22 🇬🇧 🇬🇧 United Kingdom, Maidenhead | [BL]"
      - "23 🇱🇻 🌐 Anycast-IP | 🇨🇭 🇫🇮 🇸🇪 | [BL]"
      - "24 🌐 Anycast-IP | 🇨🇭 🇸🇪 | [BL]"
      - "25 🇺🇸 🌐 Anycast-IP | 🇬🇧 🇺🇸 | [BL]"
      - "26 🇷🇺 🌐 Anycast-IP | 🇩🇪 🇷🇺 🇸🇨 | [BL]"
      - "27 🇫🇷 🇫🇷 France, Lyon | [BL]"
      - "28 🇯🇵 Japan, Shibuya City | [BL]"
      - "29 🇯🇵 Japan, Shibuya City | [BL]"
      - "30 🇱🇻 Latvia, Riga | [BL]"
      - "31 🇹🇷 Turkey, Yakuplu | [BL]"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 🇨🇦 Canada, Toronto | 🌐 | [BL]"
      - "2 🇷🇴 🇷🇴 Romania, Bucharest | 🌐 | [BL]"
      - "3 🇸🇬 Singapore, Singapore | [BL]"
      - "4 🇸🇬 🇸🇬 Singapore, Singapore | [BL]"
      - "5 🇸🇬 🇸🇬 Singapore, Singapore | [BL]"
      - "6 🇸🇬 🇸🇬 Singapore, Singapore | [BL]"
      - "7 🇸🇬 🇸🇬 Singapore, Singapore (Loyang) | 🌐 | [BL]"
      - "8 🇰🇷 🇰🇷 South Korea, Yangcheondong | [BL]"
      - "9 🇸🇪 Sweden, Stockholm | 🌐 | [BL]"
      - "10 🇳🇱 The Netherlands, Amsterdam | [BL]"
      - "11 🇺🇸 🇺🇸 United States | 🌐 | [BL]"
      - "12 🇺🇸 🇺🇸 United States, San Jose | 🌐 | [BL]"
      - "13 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]"
      - "14 🇲🇩 Moldova, Chisinau | [BL]"
      - "15 🇳🇴 🇳🇴 Norway, Sandefjord | [BL]"
      - "16 🇺🇸 🇳🇱 The Netherlands, Schiphol-Rijk | [BL]"
      - "17 🇳🇱 The Netherlands, Schiphol-Rijk | [BL]"
      - "18 🇹🇷 Turkey, Istanbul | [BL]"
      - "19 🇹🇷 Turkey, Istanbul | [BL]"
      - "20 🇹🇷 Turkey, Yakuplu | [BL]"
      - "21 🇹🇷 Turkey, Yakuplu | [BL]"
      - "22 🇬🇧 🇬🇧 United Kingdom, Maidenhead | [BL]"
      - "23 🇱🇻 🌐 Anycast-IP | 🇨🇭 🇫🇮 🇸🇪 | [BL]"
      - "24 🌐 Anycast-IP | 🇨🇭 🇸🇪 | [BL]"
      - "25 🇺🇸 🌐 Anycast-IP | 🇬🇧 🇺🇸 | [BL]"
      - "26 🇷🇺 🌐 Anycast-IP | 🇩🇪 🇷🇺 🇸🇨 | [BL]"
      - "27 🇫🇷 🇫🇷 France, Lyon | [BL]"
      - "28 🇯🇵 Japan, Shibuya City | [BL]"
      - "29 🇯🇵 Japan, Shibuya City | [BL]"
      - "30 🇱🇻 Latvia, Riga | [BL]"
      - "31 🇹🇷 Turkey, Yakuplu | [BL]"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
