global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]","type":"hysteria2","server":"us5.h1cloud.net","port":25172,"password":"Hd7N0TU7Ow5ZqaIx"}
  - {"name":"2 🇩🇪 Germany, Frankfurt am Main | [BL]","type":"hysteria2","server":"de12.h1cloud.net","port":25096,"password":"UfRjQpXI5OzVXsOy"}
  - {"name":"3 🇭🇰 Hong Kong, Central | [BL]","type":"hysteria2","server":"50dc16b5-tmm5c0-tmj4pk-1kcpe.hk3.hyhuawei.com","port":443,"password":"3f514ea2-4662-11ed-a8bf-f23c91cfbbc9"}
  - {"name":"4 🇷🇺 Russia, Moscow | [BL]","type":"hysteria2","server":"msk.frkn.org","port":443,"password":"f317b5d6-d399-4d3d-a051-89d674ae953c"}
  - {"name":"5 🇺🇸 🇫🇮 Finland, Helsinki | 🌐 | [BL]","type":"vless","server":"199.232.239.239","port":443,"uuid":"71a195c5-df47-47ad-81be-f4d3a3a21be3","udp":true,"tls":true,"network":"xhttp","servername":"ssl.fastly.com"}
  - {"name":"6 🇸🇬 Singapore | 🌐 | [BL]","type":"vless","server":"support.zoom.us","port":8443,"uuid":"ba9ba1d3-19c8-4792-9d3f-ddd2cdcc2e65","udp":true,"tls":true,"network":"ws","servername":"primelinelk.me"}
  - {"name":"7 🇸🇬 Singapore, Singapore | 🌐 | [BL]","type":"vless","server":"news.zoom.us","port":8443,"uuid":"799b1006-3255-4e36-8ea0-64fe24d2bfa7","udp":true,"tls":true,"network":"ws","servername":"asia.csmaster.site"}
  - {"name":"8 🇺🇸 🇸🇬 Singapore, Singapore | 🌐 | [BL]","type":"vless","server":"170.114.52.22","port":443,"uuid":"a853e120-3570-462b-aec1-e8f3d4f92d24","udp":true,"tls":true,"network":"ws"}
  - {"name":"9 🇹🇼 Taiwan, Taipei | [BL]","type":"vless","server":"hinet1.2yly.com","port":24215,"uuid":"19d5a678-8396-4e3b-93da-ece618d0e83a","udp":true,"tls":true,"network":"raw","servername":"addons.mozilla.org"}
  - {"name":"10 🇰🇿 🇬🇧 United Kingdom, London | 🌐 | [BL]","type":"vless","server":"83.97.77.63","port":2053,"uuid":"e0ca1d04-d2a2-418d-835f-38e44f3fcfbb","udp":true,"tls":true,"network":"ws","servername":"QjSDgI-6551.gborole.buzz"}
  - {"name":"11 🇳🇱 🌐 Anycast-IP | 🇦🇷 🇨🇦 🇩🇪 🇮🇪 🇳🇱 | [BL]","type":"vless","server":"188.164.248.216","port":443,"uuid":"d342d11e-d224-4463-b982-532309285094","udp":true,"tls":true,"network":"ws","servername":"ccc.010304.xyz"}
  - {"name":"12 🇳🇱 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]","type":"trojan","server":"188.42.145.180","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"13 🇺🇸 🇫🇷 France, Paris | [BL]","type":"trojan","server":"141.193.213.172","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"14 🇺🇸 🇫🇷 France, Paris | [BL]","type":"trojan","server":"45.205.0.6","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"15 🇩🇪 🇫🇷 France, Paris | [BL]","type":"trojan","server":"45.80.111.7","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"16 🇦🇪 United Arab Emirates, Abu Dhabi | [BL]","type":"trojan","server":"nl.zhabulik.ru","port":443,"password":"WFer-5gN21nfHbVB2N8s71Z74EPUfzVj","udp":true,"tls":true}
  - {"name":"17 🇨🇳 🇨🇳 China, Shenzhen | [BL]","type":"vmess","server":"39.108.113.127","port":10086,"uuid":"fde10e39-48bb-4dcf-b3ba-71d711323a54","alterId":0,"cipher":"auto","udp":true}
  - {"name":"18 🇭🇰 Hong Kong, Hong Kong | [BL]","type":"vmess","server":"nycqg19zkwacpm1b.v.3dns.vip","port":443,"uuid":"f23bb427-c1f9-4373-876c-2f43e9f790f3","alterId":0,"cipher":"auto","udp":true}
  - {"name":"19 🇭🇰 Hong Kong, Hong Kong | [BL]","type":"vmess","server":"nycqg19zkwacpm1b.v.3dns.vip","port":443,"uuid":"f23bb427c1f94373876c2f43e9f790f3","alterId":0,"cipher":"auto","udp":true}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]"
      - "2 🇩🇪 Germany, Frankfurt am Main | [BL]"
      - "3 🇭🇰 Hong Kong, Central | [BL]"
      - "4 🇷🇺 Russia, Moscow | [BL]"
      - "5 🇺🇸 🇫🇮 Finland, Helsinki | 🌐 | [BL]"
      - "6 🇸🇬 Singapore | 🌐 | [BL]"
      - "7 🇸🇬 Singapore, Singapore | 🌐 | [BL]"
      - "8 🇺🇸 🇸🇬 Singapore, Singapore | 🌐 | [BL]"
      - "9 🇹🇼 Taiwan, Taipei | [BL]"
      - "10 🇰🇿 🇬🇧 United Kingdom, London | 🌐 | [BL]"
      - "11 🇳🇱 🌐 Anycast-IP | 🇦🇷 🇨🇦 🇩🇪 🇮🇪 🇳🇱 | [BL]"
      - "12 🇳🇱 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]"
      - "13 🇺🇸 🇫🇷 France, Paris | [BL]"
      - "14 🇺🇸 🇫🇷 France, Paris | [BL]"
      - "15 🇩🇪 🇫🇷 France, Paris | [BL]"
      - "16 🇦🇪 United Arab Emirates, Abu Dhabi | [BL]"
      - "17 🇨🇳 🇨🇳 China, Shenzhen | [BL]"
      - "18 🇭🇰 Hong Kong, Hong Kong | [BL]"
      - "19 🇭🇰 Hong Kong, Hong Kong | [BL]"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]"
      - "2 🇩🇪 Germany, Frankfurt am Main | [BL]"
      - "3 🇭🇰 Hong Kong, Central | [BL]"
      - "4 🇷🇺 Russia, Moscow | [BL]"
      - "5 🇺🇸 🇫🇮 Finland, Helsinki | 🌐 | [BL]"
      - "6 🇸🇬 Singapore | 🌐 | [BL]"
      - "7 🇸🇬 Singapore, Singapore | 🌐 | [BL]"
      - "8 🇺🇸 🇸🇬 Singapore, Singapore | 🌐 | [BL]"
      - "9 🇹🇼 Taiwan, Taipei | [BL]"
      - "10 🇰🇿 🇬🇧 United Kingdom, London | 🌐 | [BL]"
      - "11 🇳🇱 🌐 Anycast-IP | 🇦🇷 🇨🇦 🇩🇪 🇮🇪 🇳🇱 | [BL]"
      - "12 🇳🇱 .𖥔 ݁ ˖ִ🛸༄˖°. | [BL]"
      - "13 🇺🇸 🇫🇷 France, Paris | [BL]"
      - "14 🇺🇸 🇫🇷 France, Paris | [BL]"
      - "15 🇩🇪 🇫🇷 France, Paris | [BL]"
      - "16 🇦🇪 United Arab Emirates, Abu Dhabi | [BL]"
      - "17 🇨🇳 🇨🇳 China, Shenzhen | [BL]"
      - "18 🇭🇰 Hong Kong, Hong Kong | [BL]"
      - "19 🇭🇰 Hong Kong, Hong Kong | [BL]"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
