global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy","type":"vless","server":"104.18.37.228","port":443,"uuid":"e5cc16a6-ea42-46b2-82ae-ad2157e1641b","udp":true,"tls":true,"network":"ws","servername":"hhlfy.twiladaphne.ndjp.net"}
  - {"name":"2 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy","type":"vless","server":"169.40.42.15","port":443,"uuid":"d65cc14c-f53f-4fe2-b262-97856601319c","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"3 🇺🇸 Server 19","type":"vless","server":"169.40.42.173","port":443,"uuid":"d65cc14c-f53f-4fe2-b262-97856601319c","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"4 🇺🇸 Server 3","type":"vless","server":"169.40.42.184","port":443,"uuid":"d65cc14c-f53f-4fe2-b262-97856601319c","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"5 🇺🇸 🇺🇸 (7)","type":"vless","server":"169.40.42.179","port":443,"uuid":"d65cc14c-f53f-4fe2-b262-97856601319c","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"6 🇳🇱 اگه میخوای قطع نشی جوین شو : @farsiproxy","type":"vless","server":"51.158.206.8","port":23576,"uuid":"48ff2b70-e180-582f-8866-d9a2edeed5f5","udp":true,"tls":true,"network":"raw","servername":"fuck.rkn"}
  - {"name":"7 🇳🇱 @V2rayng_Fast","type":"vless","server":"51.158.206.25","port":23576,"uuid":"48ff2b70-e180-582f-8866-d9a2edeed5f5","udp":true,"tls":true,"network":"tcp","servername":"fuck.rkn"}
  - {"name":"8 🇳🇱 @v2ray_ccoonfigs_freee","type":"vless","server":"51.158.206.97","port":23576,"uuid":"48ff2b70-e180-582f-8866-d9a2edeed5f5","udp":true,"tls":true,"network":"tcp","servername":"fuck.rkn"}
  - {"name":"9 🇳🇱 Telegram:@config_proxy","type":"vless","server":"51.158.206.20","port":23576,"uuid":"48ff2b70-e180-582f-8866-d9a2edeed5f5","udp":true,"tls":true,"network":"tcp","servername":"fuck.rkn"}
  - {"name":"10 🇳🇱 https://t.me/VIPV2rayNGNP","type":"vless","server":"51.158.206.87","port":23576,"uuid":"48ff2b70-e180-582f-8866-d9a2edeed5f5","udp":true,"tls":true,"network":"tcp","servername":"fuck.rkn"}
  - {"name":"11 🇳🇱 @V2raysCollector 💍","type":"vless","server":"51.158.206.103","port":23576,"uuid":"48ff2b70-e180-582f-8866-d9a2edeed5f5","udp":true,"tls":true,"network":"tcp","servername":"fuck.rkn"}
  - {"name":"12 🇭🇰 🇭🇰 HK 1","type":"trojan","server":"119.246.1.143","port":443,"password":"BxceQaOe","udp":true,"tls":true}
  - {"name":"13 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy","type":"vmess","server":"165.140.216.142","port":443,"uuid":"b65a2d69-5634-42a2-e4be-54e8a6176900","alterId":0,"cipher":"auto","udp":true}
  - {"name":"14 🇺🇸 @Hope_Net-join-us-on-Telegram","type":"vmess","server":"82.198.246.250","port":180,"uuid":"d13fc2f5-3e05-4795-81eb-44143a09e552","alterId":0,"cipher":"auto","udp":true}
  - {"name":"15 🇺🇸 🇺🇸 Join+Telegram:@Farah_VPN 🇺🇸","type":"vmess","server":"82.198.246.233","port":180,"uuid":"d13fc2f5-3e05-4795-81eb-44143a09e552","alterId":0,"cipher":"auto","udp":true}
  - {"name":"16 🇨🇦 [🇨🇦]t.me/ConfigsHub","type":"vmess","server":"158.51.121.63","port":443,"uuid":"03fcc618-b93d-6796-6aed-8a38c975d581","alterId":0,"cipher":"auto","udp":true}
  - {"name":"17 🇦🇺 Channel id: @ShadowProxy66 🇦🇺","type":"ss","server":"104.156.233.234","port":27116,"cipher":"chacha20-ietf-poly1305","password":"bIOoi5TuImG2KccxV7-jcA7Cez+vun-c_E"}
  - {"name":"18 🇺🇸 United+States","type":"ss","server":"198.98.53.130","port":443,"cipher":"chacha20-ietf-poly1305","password":"eDfN7SODQceIOmIAbtJJtK"}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy"
      - "2 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy"
      - "3 🇺🇸 Server 19"
      - "4 🇺🇸 Server 3"
      - "5 🇺🇸 🇺🇸 (7)"
      - "6 🇳🇱 اگه میخوای قطع نشی جوین شو : @farsiproxy"
      - "7 🇳🇱 @V2rayng_Fast"
      - "8 🇳🇱 @v2ray_ccoonfigs_freee"
      - "9 🇳🇱 Telegram:@config_proxy"
      - "10 🇳🇱 https://t.me/VIPV2rayNGNP"
      - "11 🇳🇱 @V2raysCollector 💍"
      - "12 🇭🇰 🇭🇰 HK 1"
      - "13 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy"
      - "14 🇺🇸 @Hope_Net-join-us-on-Telegram"
      - "15 🇺🇸 🇺🇸 Join+Telegram:@Farah_VPN 🇺🇸"
      - "16 🇨🇦 [🇨🇦]t.me/ConfigsHub"
      - "17 🇦🇺 Channel id: @ShadowProxy66 🇦🇺"
      - "18 🇺🇸 United+States"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy"
      - "2 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy"
      - "3 🇺🇸 Server 19"
      - "4 🇺🇸 Server 3"
      - "5 🇺🇸 🇺🇸 (7)"
      - "6 🇳🇱 اگه میخوای قطع نشی جوین شو : @farsiproxy"
      - "7 🇳🇱 @V2rayng_Fast"
      - "8 🇳🇱 @v2ray_ccoonfigs_freee"
      - "9 🇳🇱 Telegram:@config_proxy"
      - "10 🇳🇱 https://t.me/VIPV2rayNGNP"
      - "11 🇳🇱 @V2raysCollector 💍"
      - "12 🇭🇰 🇭🇰 HK 1"
      - "13 🇺🇸 اگه میخوای قطع نشی جوین شو : @farsiproxy"
      - "14 🇺🇸 @Hope_Net-join-us-on-Telegram"
      - "15 🇺🇸 🇺🇸 Join+Telegram:@Farah_VPN 🇺🇸"
      - "16 🇨🇦 [🇨🇦]t.me/ConfigsHub"
      - "17 🇦🇺 Channel id: @ShadowProxy66 🇦🇺"
      - "18 🇺🇸 United+States"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
