global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 🔵@chillguy_vpn","type":"vless","server":"89.169.39.55","port":443,"uuid":"c61ec320-29f1-4e00-9272-8b676e6957b4","udp":true,"tls":true,"network":"tcp","servername":"max.ru"}
  - {"name":"2 VLESS 320 t.me/iProxyChannel","type":"vless","server":"wstg.datasynctrue.online","port":443,"uuid":"ff0b6ba8-bed0-4c4d-bbc9-23af47582615","udp":true,"tls":true,"network":"ws","servername":"wstg.datasynctrue.online"}
  - {"name":"3 VLESS 343 t.me/iProxyChannel","type":"vless","server":"213.219.212.112","port":443,"uuid":"ec2aaf4f-b1aa-4410-4b14-d4b4e9b5daf4","udp":true,"tls":true,"network":"tcp","servername":"eh.vk.ru"}
  - {"name":"4 🔵@chillguy_vpn","type":"vless","server":"love.ns.cloudflare.com","port":443,"uuid":"f7e3ff36-276c-4477-b6d4-47257500d869","udp":true,"tls":true,"network":"ws","servername":"pon.antalmani.mm.am"}
  - {"name":"5 Channel id: @internet_azad_2026","type":"vless","server":"www.speedtest.net","port":443,"uuid":"f7e3ff36-276c-4477-b6d4-47257500d869","udp":true,"tls":true,"network":"ws","servername":"pon.antalmani.mm.am"}
  - {"name":"6 🔵@chillguy_vpn","type":"vless","server":"114.129.43.30","port":8880,"uuid":"6202b230-417c-4d8e-b624-0f71afa9c75d","udp":true,"tls":false,"network":"ws"}
  - {"name":"7 🇺🇸US-🚀@VPNine1","type":"vless","server":"162.120.94.30","port":8880,"uuid":"6202b230-417c-4d8e-b624-0f71afa9c75d","udp":true,"tls":false,"network":"ws"}
  - {"name":"8 🇸🇮SI-🚀@VPNine1","type":"vless","server":"92.53.189.40","port":8880,"uuid":"6202b230-417c-4d8e-b624-0f71afa9c75d","udp":true,"tls":false,"network":"ws"}
  - {"name":"9 🇳🇱NL-🚀@VPNine1","type":"vless","server":"185.229.191.38","port":8443,"uuid":"394f6981-a782-4779-9a85-e6cf22935d93","udp":true,"tls":true,"network":"tcp","servername":"ams1.fromblancwithlove.com"}
  - {"name":"10 @v2reya88","type":"vless","server":"185.229.191.53","port":8443,"uuid":"394f6981-a782-4779-9a85-e6cf22935d93","udp":true,"tls":true,"network":"tcp","servername":"ams1.fromblancwithlove.com"}
  - {"name":"11 𝗝𝗼𝗶𝗻 ➠ @Daily_Configs ☄️","type":"vless","server":"46.229.243.137","port":8443,"uuid":"931729a8-3c20-4841-89a1-f18dc9ce0a6f","udp":true,"tls":true,"network":"tcp","servername":"cdn3-87.vk-cdnvideo.com"}
  - {"name":"12 @v2reya88","type":"vless","server":"77.74.123.163","port":8443,"uuid":"931729a8-3c20-4841-89a1-f18dc9ce0a6f","udp":true,"tls":true,"network":"tcp","servername":"cdn3-87.vk-cdnvideo.com"}
  - {"name":"13 @v2reya88","type":"vless","server":"185.229.191.69","port":8443,"uuid":"394f6981-a782-4779-9a85-e6cf22935d93","udp":true,"tls":true,"network":"tcp","servername":"ams1.fromblancwithlove.com"}
  - {"name":"14 🔵@chillguy_vpn","type":"vless","server":"83.168.71.216","port":443,"uuid":"a18f7c2d-9e45-4b8a-af3c-1d5e7f9c8b2a","udp":true,"tls":true,"network":"tcp","servername":"ads.x5.ru"}
  - {"name":"15 ☢️ @Troll_Hastam`","type":"vless","server":"flat-night-edd0.hosein9saleazhuongooyeh87.workers.dev","port":443,"uuid":"49c0ae46-767c-47d1-9703-8740e0c4b15a","udp":true,"tls":true,"network":"ws","servername":"FLAT-night-EDD0.hOsEin9saLEAZhuongOoYeH87.wOrkerS.DeV"}
  - {"name":"16 🔵@chillguy_vpn","type":"vless","server":"cdn9-33.vk-cdnvideo.com","port":8443,"uuid":"931729a8-3c20-4841-89a1-f18dc9ce0a6f","udp":true,"tls":true,"network":"tcp","servername":"cdn9-33.vk-cdnvideo.com"}
  - {"name":"17 🔵@chillguy_vpn","type":"vless","server":"46.229.243.149","port":8443,"uuid":"931729a8-3c20-4841-89a1-f18dc9ce0a6f","udp":true,"tls":true,"network":"tcp","servername":"cdn9-33.vk-cdnvideo.com"}
  - {"name":"18 🔵@chillguy_vpn","type":"vless","server":"45.130.125.126","port":443,"uuid":"b69b43d1-091d-4d7c-90b2-7a8bbad9d6a9","udp":true,"tls":true,"network":"ws","servername":"BItter-CreDIT-61b8.b76EbA0aBb.wORkerS.dEv"}
  - {"name":"19 🇸🇨SC-🚀@V2Ray_Hub1200","type":"vless","server":"45.130.125.162","port":443,"uuid":"f106648e-0644-40bc-974c-6edc966fe18d","udp":true,"tls":true,"network":"ws","servername":"ssd.mojaz-persian-music.ir"}
  - {"name":"20 🔵@chillguy_vpn","type":"vless","server":"108.162.194.119","port":443,"uuid":"f7e3ff36-276c-4477-b6d4-47257500d869","udp":true,"tls":true,"network":"ws","servername":"pon.antalmani.mm.am"}
  - {"name":"21 🔵@chillguy_vpn","type":"vless","server":"172.64.34.119","port":443,"uuid":"f7e3ff36-276c-4477-b6d4-47257500d869","udp":true,"tls":true,"network":"ws","servername":"pon.antalmani.mm.am"}
  - {"name":"22 🔵@chillguy_vpn","type":"vless","server":"skk.moe","port":443,"uuid":"f7e3ff36-276c-4477-b6d4-47257500d869","udp":true,"tls":true,"network":"ws","servername":"pon.antalmani.mm.am"}
  - {"name":"23 🔵@chillguy_vpn","type":"vless","server":"141.193.213.10","port":443,"uuid":"f7e3ff36-276c-4477-b6d4-47257500d869","udp":true,"tls":true,"network":"ws","servername":"pon.antalmani.mm.am"}
  - {"name":"24 🔵@chillguy_vpn","type":"vless","server":"199.181.197.176","port":443,"uuid":"f7e3ff36-276c-4477-b6d4-47257500d869","udp":true,"tls":true,"network":"ws","servername":"pon.antalmani.mm.am"}
  - {"name":"25 VIP -zgtxq96gt2","type":"vmess","server":"89.167.82.102","port":8880,"uuid":"38d5f36b-b393-4e3f-a150-4937935c6bb1","alterId":0,"cipher":"auto","udp":true}
  - {"name":"26 VIP -4a65tdkc28","type":"vmess","server":"89.167.82.102","port":8880,"uuid":"e7cb49ba-163b-42ff-861e-a409deb4ece5","alterId":0,"cipher":"auto","udp":true}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 🔵@chillguy_vpn"
      - "2 VLESS 320 t.me/iProxyChannel"
      - "3 VLESS 343 t.me/iProxyChannel"
      - "4 🔵@chillguy_vpn"
      - "5 Channel id: @internet_azad_2026"
      - "6 🔵@chillguy_vpn"
      - "7 🇺🇸US-🚀@VPNine1"
      - "8 🇸🇮SI-🚀@VPNine1"
      - "9 🇳🇱NL-🚀@VPNine1"
      - "10 @v2reya88"
      - "11 𝗝𝗼𝗶𝗻 ➠ @Daily_Configs ☄️"
      - "12 @v2reya88"
      - "13 @v2reya88"
      - "14 🔵@chillguy_vpn"
      - "15 ☢️ @Troll_Hastam`"
      - "16 🔵@chillguy_vpn"
      - "17 🔵@chillguy_vpn"
      - "18 🔵@chillguy_vpn"
      - "19 🇸🇨SC-🚀@V2Ray_Hub1200"
      - "20 🔵@chillguy_vpn"
      - "21 🔵@chillguy_vpn"
      - "22 🔵@chillguy_vpn"
      - "23 🔵@chillguy_vpn"
      - "24 🔵@chillguy_vpn"
      - "25 VIP -zgtxq96gt2"
      - "26 VIP -4a65tdkc28"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 🔵@chillguy_vpn"
      - "2 VLESS 320 t.me/iProxyChannel"
      - "3 VLESS 343 t.me/iProxyChannel"
      - "4 🔵@chillguy_vpn"
      - "5 Channel id: @internet_azad_2026"
      - "6 🔵@chillguy_vpn"
      - "7 🇺🇸US-🚀@VPNine1"
      - "8 🇸🇮SI-🚀@VPNine1"
      - "9 🇳🇱NL-🚀@VPNine1"
      - "10 @v2reya88"
      - "11 𝗝𝗼𝗶𝗻 ➠ @Daily_Configs ☄️"
      - "12 @v2reya88"
      - "13 @v2reya88"
      - "14 🔵@chillguy_vpn"
      - "15 ☢️ @Troll_Hastam`"
      - "16 🔵@chillguy_vpn"
      - "17 🔵@chillguy_vpn"
      - "18 🔵@chillguy_vpn"
      - "19 🇸🇨SC-🚀@V2Ray_Hub1200"
      - "20 🔵@chillguy_vpn"
      - "21 🔵@chillguy_vpn"
      - "22 🔵@chillguy_vpn"
      - "23 🔵@chillguy_vpn"
      - "24 🔵@chillguy_vpn"
      - "25 VIP -zgtxq96gt2"
      - "26 VIP -4a65tdkc28"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
