global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 🐒55@unvisible_drops","type":"vless","server":"pqh18v7.viripdirect.shop","port":8880,"uuid":"8dc7722c-2767-4eea-a28b-2f8daacc07e3","udp":true,"tls":false,"network":"grpc"}
  - {"name":"2 @chillguy_vpn","type":"vless","server":"15.204.97.197","port":23576,"uuid":"48ff2b70-e180-582f-8866-d9a2edeed5f5","udp":true,"tls":true,"network":"tcp","servername":"fuck.rkn"}
  - {"name":"3 𝐉𝐨𝐢𝐧➠@𝘁𝗲𝗹𝗲𝗿𝗮𝘆𝘃𝗽𝗻 :کانال تلگرام⚡️","type":"vless","server":"94.232.247.168","port":41360,"uuid":"e16a35ea-6715-4e75-9845-d20358bd0876","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"4 @chillguy_vpn","type":"vless","server":"45.88.182.24","port":25380,"uuid":"237120d4-6f8e-47de-b50c-2c8218a720df","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"5 🔆 Tel : @ProxyVPN11 ⟵","type":"vless","server":"157.173.127.225","port":443,"uuid":"11beaf11-726d-4c11-8ce9-27308c1c608c","udp":true,"tls":true,"network":"tcp","servername":"analytics.google.com"}
  - {"name":"6 تو کانال نتورلد نباشید قطع میشن\n@irmeliy","type":"vless","server":"45.136.149.145","port":443,"uuid":"ddb913e5-492f-42e8-baec-93c9c5d333d6","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"7 📅12/08-@v2node👉🏻17","type":"vless","server":"81.88.25.20","port":59029,"uuid":"c031d6c7-5132-4d81-8efc-3b13a947984e","udp":true,"tls":false,"network":"tcp"}
  - {"name":"8 @chillguy_vpn","type":"vless","server":"152.53.116.71","port":443,"uuid":"1e878456-0f00-4a85-99a6-1d69bdc62e3d","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"9 @Dynamite_vpn","type":"vless","server":"151.115.96.243","port":7242,"uuid":"859b7d71-a9fc-4234-8e03-42eb876a170a","udp":true,"tls":true,"network":"tcp","servername":"modily.net"}
  - {"name":"10 🦉@FreeConfigForYou","type":"vless","server":"103.245.237.124","port":58202,"uuid":"cca053d5-7123-4a87-83d6-babe4e9c8115","udp":true,"tls":false,"network":"ws"}
  - {"name":"11 @v2_mod_shop (تلگرام)","type":"vless","server":"152.53.48.237","port":22955,"uuid":"63f92f3c-447c-4283-80b9-0af8e164cdad","udp":true,"tls":true,"network":"grpc","servername":"one-piece.com"}
  - {"name":"12 @v2_mod_shop (تلگرام)","type":"vless","server":"norman.ns.cloudflare.com","port":443,"uuid":"94daa8ad-75ed-4dbf-a6de-d05036d98df5","udp":true,"tls":true,"network":"ws","servername":"vangoghhh.info"}
  - {"name":"13 @Caa_family|نمونه کانفیگ چت جی پی تی**","type":"vless","server":"chatgpt.com","port":2083,"uuid":"6a719f2b-b629-462d-975a-9c0daa3edb75","udp":true,"tls":true,"network":"ws","servername":"rAviDdD.paGEs.DEv"}
  - {"name":"14 @v2_mod_shop (تلگرام)`","type":"vless","server":"5.182.38.91","port":17267,"uuid":"1c7fcc38-e6be-43c5-875f-b8de2516b9f2","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"15 ⚡ @HajmVPN_Config","type":"vless","server":"plcdn23.suio.me","port":443,"uuid":"62ad5a48-f452-4868-b7eb-d27df9b3d723","udp":true,"tls":true,"network":"tcp","servername":"plcdn23.suio.me"}
  - {"name":"16 @v2_mod_shop (تلگرام)`","type":"vless","server":"188.114.98.0","port":2087,"uuid":"3f58cc47-94f6-40d3-8797-1ce66cb0555e","udp":true,"tls":true,"network":"ws","servername":"nl4.maxriser.ir"}
  - {"name":"17 @mtproto_proserver","type":"vless","server":"157.254.223.44","port":18959,"uuid":"d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa","udp":true,"tls":true,"network":"tcp","servername":"itunes.apple.com"}
  - {"name":"18 @airdrop2033`","type":"vless","server":"3.fr.vles.space","port":23151,"uuid":"7f37b28b-cfcb-4c2a-ae41-8f2ddc9325dd","udp":true,"tls":true,"network":"tcp","servername":"cms-res-web.online.sberbank.ru"}
  - {"name":"19 [🇳🇱]/","type":"vless","server":"89.149.243.207","port":443,"uuid":"6e342451-814c-4f51-803c-59107f0540f2","udp":true,"tls":true,"network":"tcp","servername":"www.apple.com"}
  - {"name":"20 🏴🏳5","type":"ss","server":"82.38.31.122","port":8080,"cipher":"chacha20-ietf-poly1305","password":"oZIoA69Q8yhcQV8ka3Pa3A"}
  - {"name":"21 🇬🇧 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳```","type":"ss","server":"46.250.254.170","port":443,"cipher":"aes-256-gcm","password":"BedufgztHO3B5Kqe"}
  - {"name":"22 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳","type":"ss","server":"154.53.63.32","port":80,"cipher":"aes-256-gcm","password":"k6ruJuwgAUxIrkHb"}
  - {"name":"23 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳","type":"ss","server":"154.53.60.197","port":80,"cipher":"aes-256-gcm","password":"8rb580EBG4l7tO8K"}
  - {"name":"24 📅12/09-@v2node👉🏻36","type":"ss","server":"112.197.26.106","port":45313,"cipher":"chacha20-ietf-poly1305","password":"ca5a5efae00a832b"}
  - {"name":"25 📅12/09-@v2node👉🏻38","type":"ss","server":"112.197.26.106","port":26417,"cipher":"chacha20-ietf-poly1305","password":"fd7b0d14b590bceb"}
  - {"name":"26 📅12/09-@v2node👉🏻39","type":"ss","server":"112.197.26.106","port":45310,"cipher":"chacha20-ietf-poly1305","password":"ca5a5efae00a832b"}
  - {"name":"27 📅12/09-@v2node👉🏻40","type":"ss","server":"112.197.26.106","port":45311,"cipher":"chacha20-ietf-poly1305","password":"ca5a5efae00a832b"}
  - {"name":"28 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳","type":"ss","server":"124.217.247.205","port":51348,"cipher":"chacha20-ietf-poly1305","password":"RZirHzSqyyb37DDIiQeDLZTJft5ZQGmUCwyA3wm5ath4j9Y3"}
  - {"name":"29 🇳🇱NL  ROSE—25```","type":"ss","server":"82.38.31.35","port":8080,"cipher":"chacha20-ietf-poly1305","password":"oZIoA69Q8yhcQV8ka3Pa3A"}
  - {"name":"30 @i10VPN 🚀| با ما متصل بمون⚡","type":"ss","server":"141.95.106.127","port":11201,"cipher":"chacha20-ietf-poly1305","password":"94aae0510188e8c5"}
  - {"name":"31 @v2rayconfigamir 4101`","type":"ss","server":"154.205.146.153","port":990,"cipher":"chacha20-ietf-poly1305","password":"ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=\r��"}
  - {"name":"32 @i10VPN 🚀| با ما متصل بمون⚡","type":"ss","server":"5.181.2.76","port":36608,"cipher":"chacha20-ietf-poly1305","password":"JOZ5Mb3nJCmmoKhd8Cc9aC"}
  - {"name":"33 『  🌟@airdrop2033 』عضو کانال تلگرامی بشین`","type":"ss","server":"38.54.59.16","port":11201,"cipher":"chacha20-ietf-poly1305","password":"6ff1423f61ffe673"}
  - {"name":"34 @v2rayconfigamir 1398","type":"ss","server":"138.186.142.80","port":990,"cipher":"chacha20-ietf-poly1305","password":"ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44="}
  - {"name":"35 🦉@FreeConfigForYou","type":"ss","server":"82.38.31.194","port":8080,"cipher":"chacha20-ietf-poly1305","password":"k1dBOmOB4oqi7Ump37a1bQ"}
  - {"name":"36 🦉@FreeConfigForYou","type":"ss","server":"163.171.207.11","port":29464,"cipher":"chacha20-ietf-poly1305","password":"cb4258dc1b53613c"}
  - {"name":"37 🦉@FreeConfigForYou`","type":"ss","server":"149.104.71.134","port":11201,"cipher":"chacha20-ietf-poly1305","password":"1e68d4bd002437ab"}
  - {"name":"38 🇬🇧 UK | @KIA_NET چنل‌تلگرم","type":"ss","server":"82.38.31.62","port":8080,"cipher":"chacha20-ietf-poly1305","password":"oZIoA69Q8yhcQV8ka3Pa3A"}
  - {"name":"39 🇺🇸 USA | @KIA_NET چنل‌تلگرم","type":"ss","server":"tinkered-pennies-puppies.freesocks.work","port":443,"cipher":"chacha20-ietf-poly1305","password":"hbGrpfvNrJsUmKmPbR3iY2"}
  - {"name":"40 🌐 WS-TLS | @Express_alaki | src @V2rayProxy","type":"trojan","server":"104.18.32.47","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"41 🌐 WS-TLS | @Express_alaki | src @v2Line","type":"trojan","server":"104.21.40.34","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"42 🌐 WS-TLS | @Express_alaki | src @v2Line","type":"trojan","server":"172.64.152.23","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"43 @hi_proxy_iran :👈کانال تلگرام","type":"trojan","server":"188.114.98.0","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"44 @V2ray_confiig`","type":"trojan","server":"188.114.96.3","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"45 📅12/09-@v2node👉🏻48","type":"trojan","server":"www.multiplydose.com","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"46 برای اتصال دائمی جوین شو🚏 TelegramID ⌲SHOP_GAMING1011 🪩","type":"trojan","server":"172.67.180.92","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"47 @chillguy_vpn","type":"vmess","server":"51.79.102.253","port":80,"uuid":"58fe1542-5290-40ad-815a-77707a81afe5","alterId":0,"cipher":"auto","udp":true}
  - {"name":"48 fevomry9","type":"vmess","server":"94.232.247.164","port":44030,"uuid":"22c396a3-95da-4be8-beef-834d17d75784","alterId":0,"cipher":"auto","udp":true}
  - {"name":"49 🇷🇺 KIA_NET | Basic","type":"vmess","server":"45.89.52.207","port":39651,"uuid":"ac4c12c5-45f2-4398-a718-9983941ede2b","alterId":0,"cipher":"auto","udp":true}
  - {"name":"50 @gilass_on 🍒۹","type":"vmess","server":"46.246.126.154","port":443,"uuid":"f2fd0786-1059-4f64-d54e-3f3a568c6c68","alterId":0,"cipher":"auto","udp":true}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 🐒55@unvisible_drops"
      - "2 @chillguy_vpn"
      - "3 𝐉𝐨𝐢𝐧➠@𝘁𝗲𝗹𝗲𝗿𝗮𝘆𝘃𝗽𝗻 :کانال تلگرام⚡️"
      - "4 @chillguy_vpn"
      - "5 🔆 Tel : @ProxyVPN11 ⟵"
      - "6 تو کانال نتورلد نباشید قطع میشن
@irmeliy"
      - "7 📅12/08-@v2node👉🏻17"
      - "8 @chillguy_vpn"
      - "9 @Dynamite_vpn"
      - "10 🦉@FreeConfigForYou"
      - "11 @v2_mod_shop (تلگرام)"
      - "12 @v2_mod_shop (تلگرام)"
      - "13 @Caa_family|نمونه کانفیگ چت جی پی تی**"
      - "14 @v2_mod_shop (تلگرام)`"
      - "15 ⚡ @HajmVPN_Config"
      - "16 @v2_mod_shop (تلگرام)`"
      - "17 @mtproto_proserver"
      - "18 @airdrop2033`"
      - "19 [🇳🇱]/"
      - "20 🏴🏳5"
      - "21 🇬🇧 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳```"
      - "22 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳"
      - "23 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳"
      - "24 📅12/09-@v2node👉🏻36"
      - "25 📅12/09-@v2node👉🏻38"
      - "26 📅12/09-@v2node👉🏻39"
      - "27 📅12/09-@v2node👉🏻40"
      - "28 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳"
      - "29 🇳🇱NL  ROSE—25```"
      - "30 @i10VPN 🚀| با ما متصل بمون⚡"
      - "31 @v2rayconfigamir 4101`"
      - "32 @i10VPN 🚀| با ما متصل بمون⚡"
      - "33 『  🌟@airdrop2033 』عضو کانال تلگرامی بشین`"
      - "34 @v2rayconfigamir 1398"
      - "35 🦉@FreeConfigForYou"
      - "36 🦉@FreeConfigForYou"
      - "37 🦉@FreeConfigForYou`"
      - "38 🇬🇧 UK | @KIA_NET چنل‌تلگرم"
      - "39 🇺🇸 USA | @KIA_NET چنل‌تلگرم"
      - "40 🌐 WS-TLS | @Express_alaki | src @V2rayProxy"
      - "41 🌐 WS-TLS | @Express_alaki | src @v2Line"
      - "42 🌐 WS-TLS | @Express_alaki | src @v2Line"
      - "43 @hi_proxy_iran :👈کانال تلگرام"
      - "44 @V2ray_confiig`"
      - "45 📅12/09-@v2node👉🏻48"
      - "46 برای اتصال دائمی جوین شو🚏 TelegramID ⌲SHOP_GAMING1011 🪩"
      - "47 @chillguy_vpn"
      - "48 fevomry9"
      - "49 🇷🇺 KIA_NET | Basic"
      - "50 @gilass_on 🍒۹"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 🐒55@unvisible_drops"
      - "2 @chillguy_vpn"
      - "3 𝐉𝐨𝐢𝐧➠@𝘁𝗲𝗹𝗲𝗿𝗮𝘆𝘃𝗽𝗻 :کانال تلگرام⚡️"
      - "4 @chillguy_vpn"
      - "5 🔆 Tel : @ProxyVPN11 ⟵"
      - "6 تو کانال نتورلد نباشید قطع میشن
@irmeliy"
      - "7 📅12/08-@v2node👉🏻17"
      - "8 @chillguy_vpn"
      - "9 @Dynamite_vpn"
      - "10 🦉@FreeConfigForYou"
      - "11 @v2_mod_shop (تلگرام)"
      - "12 @v2_mod_shop (تلگرام)"
      - "13 @Caa_family|نمونه کانفیگ چت جی پی تی**"
      - "14 @v2_mod_shop (تلگرام)`"
      - "15 ⚡ @HajmVPN_Config"
      - "16 @v2_mod_shop (تلگرام)`"
      - "17 @mtproto_proserver"
      - "18 @airdrop2033`"
      - "19 [🇳🇱]/"
      - "20 🏴🏳5"
      - "21 🇬🇧 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳```"
      - "22 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳"
      - "23 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳"
      - "24 📅12/09-@v2node👉🏻36"
      - "25 📅12/09-@v2node👉🏻38"
      - "26 📅12/09-@v2node👉🏻39"
      - "27 📅12/09-@v2node👉🏻40"
      - "28 🌎 | 👉👉 @𝗫𝘃𝗽𝗻𝗽𝗹𝘂𝘀_𝗯𝗼𝘁 👈👈 |🟢 𝚃𝙴𝚂𝚃𝙴𝙳"
      - "29 🇳🇱NL  ROSE—25```"
      - "30 @i10VPN 🚀| با ما متصل بمون⚡"
      - "31 @v2rayconfigamir 4101`"
      - "32 @i10VPN 🚀| با ما متصل بمون⚡"
      - "33 『  🌟@airdrop2033 』عضو کانال تلگرامی بشین`"
      - "34 @v2rayconfigamir 1398"
      - "35 🦉@FreeConfigForYou"
      - "36 🦉@FreeConfigForYou"
      - "37 🦉@FreeConfigForYou`"
      - "38 🇬🇧 UK | @KIA_NET چنل‌تلگرم"
      - "39 🇺🇸 USA | @KIA_NET چنل‌تلگرم"
      - "40 🌐 WS-TLS | @Express_alaki | src @V2rayProxy"
      - "41 🌐 WS-TLS | @Express_alaki | src @v2Line"
      - "42 🌐 WS-TLS | @Express_alaki | src @v2Line"
      - "43 @hi_proxy_iran :👈کانال تلگرام"
      - "44 @V2ray_confiig`"
      - "45 📅12/09-@v2node👉🏻48"
      - "46 برای اتصال دائمی جوین شو🚏 TelegramID ⌲SHOP_GAMING1011 🪩"
      - "47 @chillguy_vpn"
      - "48 fevomry9"
      - "49 🇷🇺 KIA_NET | Basic"
      - "50 @gilass_on 🍒۹"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
