global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
proxies:
  - {"name":"2-v2ray_dalghak","type":"trojan","server":"185.18.250.252","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"2-@vpnbaz | نت ملی","type":"trojan","server":"chatgpt.com","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"2-(@VmessProtocol)برای خرید و اتصال دائمی جوین شو🇩🇪","type":"vmess","server":"57.129.28.63","port":443,"uuid":"03fcc618-b93d-6796-6aed-8a38c975d581","alterId":0,"cipher":"auto","udp":true}
  - {"name":"2-Channel id: @proxy_kafee🇩🇪","type":"vmess","server":"57.129.28.216","port":443,"uuid":"03fcc618-b93d-6796-6aed-8a38c975d581","alterId":0,"cipher":"auto","udp":true}
  - {"name":"2-@proxy_kafee🇩🇪","type":"vmess","server":"57.129.25.22","port":443,"uuid":"03fcc618-b93d-6796-6aed-8a38c975d581","alterId":0,"cipher":"auto","udp":true}
  - {"name":"2-🇨🇦@FreakConfig","type":"vmess","server":"158.51.121.63","port":443,"uuid":"03fcc618-b93d-6796-6aed-8a38c975d581","alterId":0,"cipher":"auto","udp":true}
  - {"name":"2-[","type":"vless","server":"109.248.170.119","port":13447,"uuid":"b573cefb-7bc7-4a42-b407-b8b534e66773","udp":true,"tls":true,"network":"raw","servername":"yahoo.com"}
  - {"name":"2-💧6@oneclickvpnkeys","type":"vless","server":"140.238.100.35","port":40721,"uuid":"bf3e8944-8d26-47de-8748-b9aa74cce974","udp":true,"tls":true,"network":"tcp","servername":"yahoo.com"}
  - {"name":"2-@meli_proxyy","type":"vless","server":"157.173.127.225","port":443,"uuid":"11beaf11-726d-4c11-8ce9-27308c1c608c","udp":true,"tls":true,"network":"tcp","servername":"analytics.google.com"}
proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "Auto"
      - "DIRECT"
  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - "2-v2ray_dalghak"
      - "2-@vpnbaz | نت ملی"
      - "2-(@VmessProtocol)برای خرید و اتصال دائمی جوین شو🇩🇪"
      - "2-Channel id: @proxy_kafee🇩🇪"
      - "2-@proxy_kafee🇩🇪"
      - "2-🇨🇦@FreakConfig"
      - "2-["
      - "2-💧6@oneclickvpnkeys"
      - "2-@meli_proxyy"
rules:
  - GEOIP,IR,DIRECT
  - MATCH,Proxy
