global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 🇺🇸 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚","type":"trojan","server":"151.101.56.7","port":443,"password":"MiTiVPN","udp":true,"tls":true}
  - {"name":"2 🇺🇸 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚","type":"trojan","server":"199.232.78.160","port":443,"password":"MiTiVPN","udp":true,"tls":true}
  - {"name":"3 🇪🇸 @Shh_Proxy-New⁸","type":"trojan","server":"213.182.199.137","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"4 🇺🇸 Server 287","type":"vless","server":"208.103.161.1","port":443,"uuid":"903bb12e-ac86-414c-adf1-b9c41e213da8","udp":true,"tls":true,"network":"grpc","servername":"viju.allomroll.org"}
  - {"name":"5 🇸🇪 @Daily_Configs","type":"vless","server":"185.189.45.247","port":443,"uuid":"c6037cf7-d931-4027-af06-6bfb0f10684c","udp":true,"tls":true,"network":"tcp","servername":"apiv14.betust.net"}
  - {"name":"6 FarazV2ray@","type":"vless","server":"sv14.betust.net","port":443,"uuid":"c6037cf7-d931-4027-af06-6bfb0f10684c","udp":true,"tls":true,"network":"tcp","servername":"apiv14.betust.net"}
  - {"name":"7 🇺🇸 𝗝𝗼𝗶𝗻➠@PlanB_net","type":"vless","server":"172.64.150.28","port":2082,"uuid":"e5cc16a6-ea42-46b2-82ae-ad2157e1641b","udp":true,"tls":false,"network":"ws"}
  - {"name":"8 🇬🇧 🇩🇪  ما @v2rayNG_Matsuri","type":"vless","server":"5.152.223.193","port":443,"uuid":"9e6b8db1-da80-494f-bad7-7a0451f801a1","udp":true,"tls":true,"network":"tcp","servername":"strapi.io"}
  - {"name":"9 🇸🇰 🍏89@oneclickvpnkeys","type":"vless","server":"185.112.249.201","port":8443,"uuid":"9b18ccef-b9e0-41d1-8990-9d970569e142","udp":true,"tls":true,"network":"ws","servername":"web-socket.tgdaosheng.ggff.net"}
  - {"name":"10 🇵🇱 Poland","type":"vless","server":"54.38.138.175","port":443,"uuid":"b2e8f455-3bd9-477c-b8f0-a3198f601565","udp":true,"tls":true,"network":"tcp","servername":"play.google.com"}
  - {"name":"11 @Daily_Configs","type":"vless","server":"darsadgir.ir","port":443,"uuid":"d5af4dfe-eaf1-460c-87aa-fefe930db0ba","udp":true,"tls":true,"network":"xhttp","servername":"chopin.paxr.ir"}
  - {"name":"12 🇺🇸 Server 106","type":"vless","server":"104.17.108.59","port":443,"uuid":"903bb12e-ac86-414c-adf1-b9c41e213da8","udp":true,"tls":true,"network":"grpc","servername":"sire.allomroll.org"}
  - {"name":"13 @FarazV2ray","type":"vless","server":"rs3.univesalsrv.com","port":443,"uuid":"2f35965a-9a9b-45fd-ba32-987296dfb6be","udp":true,"tls":true,"network":"grpc","servername":"rs3.univesalsrv.com"}
  - {"name":"14 🇲🇩 @FarazV2ray","type":"vless","server":"89.35.14.32","port":443,"uuid":"2f35965a-9a9b-45fd-ba32-987296dfb6be","udp":true,"tls":true,"network":"grpc","servername":"md3.univesalsrv.com"}
  - {"name":"15 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚","type":"vless","server":"bg5.univesalsrv.com","port":443,"uuid":"2f35965a-9a9b-45fd-ba32-987296dfb6be","udp":true,"tls":true,"network":"grpc","servername":"bg5.univesalsrv.com"}
  - {"name":"16 🇨🇵","type":"vless","server":"rs1.univesalsrv.com","port":443,"uuid":"2f35965a-9a9b-45fd-ba32-987296dfb6be","udp":true,"tls":true,"network":"grpc","servername":"rs1.univesalsrv.com"}
  - {"name":"17 @v2raybaaz ²","type":"vless","server":"md5.univesalsrv.com","port":443,"uuid":"2f35965a-9a9b-45fd-ba32-987296dfb6be","udp":true,"tls":true,"network":"grpc","servername":"md5.univesalsrv.com"}
  - {"name":"18 🇷🇺 🇷🇺@FreakConfig","type":"hysteria2","server":"144.31.49.138","port":443,"password":"cd74c0a406664a5bc0bac098220a2468"}
  - {"name":"19 🇩🇪 (@VmessProtocol)برای خرید و اتصال دائمی جوین شو🇩🇪","type":"hysteria2","server":"2.27.59.206","port":443,"password":"cd74c0a406664a5bc0bac098220a2468"}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 🇺🇸 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚"
      - "2 🇺🇸 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚"
      - "3 🇪🇸 @Shh_Proxy-New⁸"
      - "4 🇺🇸 Server 287"
      - "5 🇸🇪 @Daily_Configs"
      - "6 FarazV2ray@"
      - "7 🇺🇸 𝗝𝗼𝗶𝗻➠@PlanB_net"
      - "8 🇬🇧 🇩🇪  ما @v2rayNG_Matsuri"
      - "9 🇸🇰 🍏89@oneclickvpnkeys"
      - "10 🇵🇱 Poland"
      - "11 @Daily_Configs"
      - "12 🇺🇸 Server 106"
      - "13 @FarazV2ray"
      - "14 🇲🇩 @FarazV2ray"
      - "15 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚"
      - "16 🇨🇵"
      - "17 @v2raybaaz ²"
      - "18 🇷🇺 🇷🇺@FreakConfig"
      - "19 🇩🇪 (@VmessProtocol)برای خرید و اتصال دائمی جوین شو🇩🇪"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 🇺🇸 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚"
      - "2 🇺🇸 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚"
      - "3 🇪🇸 @Shh_Proxy-New⁸"
      - "4 🇺🇸 Server 287"
      - "5 🇸🇪 @Daily_Configs"
      - "6 FarazV2ray@"
      - "7 🇺🇸 𝗝𝗼𝗶𝗻➠@PlanB_net"
      - "8 🇬🇧 🇩🇪  ما @v2rayNG_Matsuri"
      - "9 🇸🇰 🍏89@oneclickvpnkeys"
      - "10 🇵🇱 Poland"
      - "11 @Daily_Configs"
      - "12 🇺🇸 Server 106"
      - "13 @FarazV2ray"
      - "14 🇲🇩 @FarazV2ray"
      - "15 @prrofile_purple | 𝗙𝗮𝗦𝗧 💚"
      - "16 🇨🇵"
      - "17 @v2raybaaz ²"
      - "18 🇷🇺 🇷🇺@FreakConfig"
      - "19 🇩🇪 (@VmessProtocol)برای خرید و اتصال دائمی جوین شو🇩🇪"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
