global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: always
ipv6: true
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  respect-rules: false
  prefer-h3: true
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '*.ir'
 
  default-nameserver: 
    - 8.8.8.8 
    - 8.8.4.4 
    - 1.0.0.1 
    - 1.1.1.1 
    - 9.9.9.9 
    - 9.9.9.11 
    - 9.9.9.10 
    - 94.140.14.15 
    - 94.140.15.15 
    - 223.5.5.5 
    - 77.88.8.8
  nameserver:
    - 'https://sky.rethinkdns.com/1:-J8AGH8C7_2-___f3_vZ3f_z-f9KagBI'
    - 'tls://1-7cpqagd7alx73px777p5766z3x77h6p7jjvaasa.max.rethinkdns.com'
  direct-nameserver:
    - '78.157.42.100'
    - '78.157.42.101' 
  proxy-server-nameserver: 
    - '2606:4700:4700::1111' 
    - '2606:4700:4700::1001' 
    - '2001:4860:4860::8888' 
    - '2001:4860:4860::8844' 
    - '1.1.1.1' 
    - '8.8.8.8' 
    - '8.8.4.4' 
    - '9.9.9.9' 
    - '223.5.5.5' 
    - '77.88.8.8' 
    - '2400:3200::1' 
    - '2a02:6b8::feed:0ff' 
    - '2620:fe::fe' 

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080, 8880, 2052, 2082, 2086, 2095]
    TLS:
      ports: [443, 8443, 2053, 2083, 2087, 2096]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

rule-providers:
  local_ips:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/local-ips.yaml
    interval: 86400
    path: ./ruleset/local_ips.yaml
  category_ir:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/10ium/V2rayDomains2Clash/generated/category-ir.yaml
    interval: 86400
    path: ./ruleset/category_ir.yaml
  iran:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/10ium/clash_rules/main/iran.yaml
    interval: 86400
    path: ./ruleset/iran.yaml
  ir:
    type: http
    format: yaml
    behavior: domain
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ir.yaml"
    path: ./ruleset/ir.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml"
    path: ./ruleset/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/ircidr.yaml"
    path: ./ruleset/ircidr.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml"
    path: ./ruleset/irasn.yaml
    interval: 86400
  arvancloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/arvancloud.yaml"
    path: ./ruleset/arvancloud.yaml
    interval: 86400
  derakcloud:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/derakcloud.yaml"
    path: ./ruleset/derakcloud.yaml
    interval: 86400
  iranserver:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/iranserver.yaml"
    path: ./ruleset/iranserver.yaml
    interval: 86400
  parspack:
    type: http
    format: yaml
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/parspack.yaml"
    path: ./ruleset/parspack.yaml
    interval: 86400
proxies:
  - {"name":"1 `@mtproto_proserver","type":"vless","server":"104.17.72.206","port":443,"uuid":"06ef598c-1555-4887-b3f9-08214a2f6792","udp":true,"tls":true,"network":"ws","servername":"2026.hhhhh.eu.org"}
  - {"name":"2 `@mtproto_proserver","type":"vless","server":"172.64.152.23","port":443,"uuid":"06ef598c-1555-4887-b3f9-08214a2f6792","udp":true,"tls":true,"network":"ws","servername":"2026.hhhhh.eu.org"}
  - {"name":"3 @mkill_network 🤍`","type":"vless","server":"172.64.149.54","port":443,"uuid":"06ef598c-1555-4887-b3f9-08214a2f6792","udp":true,"tls":true,"network":"ws","servername":"2026.hhhhh.eu.org"}
  - {"name":"4 Telegram:++@Zero_Tunnel+7","type":"vless","server":"104.18.16.56","port":443,"uuid":"06ef598c-1555-4887-b3f9-08214a2f6792","udp":true,"tls":true,"network":"ws","servername":"2026.hhhhh.eu.org"}
  - {"name":"5 Telegram : @Config0plus🥷🇧🇷`","type":"vless","server":"8.6.112.6","port":443,"uuid":"06ef598c-1555-4887-b3f9-08214a2f6792","udp":true,"tls":true,"network":"ws","servername":"2026.hhhhh.eu.org"}
  - {"name":"6 @tik7net_vpn","type":"vless","server":"188.114.98.0","port":443,"uuid":"cff6f361-828a-43c8-a8b5-8d10b32e57fb","udp":true,"tls":true,"network":"ws","servername":"zh.hollowspot.ir"}
  - {"name":"7 تلگرام عضو شو @melibazz`","type":"vless","server":"2.56.172.83","port":8443,"uuid":"e033ef6e-ab4b-47d4-a523-ff568d2c8dbb","udp":true,"tls":true,"network":"tcp","servername":"tradingview.com"}
  - {"name":"8 @ProtoRay","type":"vless","server":"8.6.112.0","port":443,"uuid":"2c72881c-5609-4c10-999e-6f8ce8d0c2b4","udp":true,"tls":true,"network":"ws","servername":"vsgyajsb.zahramehri.ir"}
  - {"name":"9 🕳️20@oneclickvpnkeys","type":"vless","server":"95.164.85.33","port":443,"uuid":"43488128-319e-f480-64ea-0acdc712e2a8","udp":true,"tls":true,"network":"tcp","servername":"www.rakuten.co.jp"}
  - {"name":"10 🕳️5@oneclickvpnkeys","type":"vless","server":"195.181.173.199","port":8443,"uuid":"394f6981-a782-4779-9a85-e6cf22935d93","udp":true,"tls":true,"network":"tcp","servername":"ams1.fromblancwithlove.com"}
  - {"name":"11 🚹60@oneclickvpnkeys`","type":"vless","server":"18.245.54.3","port":443,"uuid":"97b2cd5b-b98d-494f-8f97-3a06e8c1bbd2","udp":true,"tls":true,"network":"ws","servername":"d23iuljn5k9z1j.cloudfront.net"}
  - {"name":"12 🇬🇧4755 | ⚡️Telegram = t.me/LonUp_M","type":"vless","server":"152.233.28.198","port":8443,"uuid":"394f6981-a782-4779-9a85-e6cf22935d93","udp":true,"tls":true,"network":"tcp","servername":"uk1.fromblancwithlove.com"}
  - {"name":"13 @v2rayconfigamir 2494","type":"vless","server":"188.214.129.172","port":443,"uuid":"1c45e98c-8a4a-45e7-acc5-3a3cc962f463","udp":true,"tls":true,"network":"tcp","servername":"flowwow.com"}
  - {"name":"14 @aloconfig_com","type":"vless","server":"104.20.6.134","port":443,"uuid":"06ef598c-1555-4887-b3f9-08214a2f6792","udp":true,"tls":true,"network":"ws","servername":"2026.hhhhh.eu.org"}
  - {"name":"15 برای اتصال دائمی جوین شو🗾 v2ray_configs_pools@","type":"vless","server":"104.20.6.134","port":443,"uuid":"26524cce-d514-4014-a426-365fb266a14d","udp":true,"tls":true,"network":"ws","servername":"snippet.danfeng.rr.kg"}
  - {"name":"16 @internet_azad_2026`","type":"vless","server":"104.20.6.134","port":443,"uuid":"13ebfdbb-8548-4468-905a-2d2265ae7cae","udp":true,"tls":true,"network":"ws","servername":"thisisverytemp.bananalegends.com"}
  - {"name":"17 T.me/MiTiVPN 4","type":"vless","server":"104.20.6.134","port":2053,"uuid":"8c4604ef-749c-4b56-adf1-7da405002a21","udp":true,"tls":true,"network":"ws","servername":"qyi.fqjd663.ggff.net"}
  - {"name":"18 melibaZz`","type":"ss","server":"tinkered-pennies-puppies.freesocks.work","port":443,"cipher":"chacha20-ietf-poly1305","password":"hbGrpfvNrJsUmKmPbR3iY2"}
  - {"name":"19 🕳️6@oneclickvpnkeys","type":"ss","server":"193.29.139.217","port":8080,"cipher":"chacha20-ietf-poly1305","password":"4a2rfixophdjffa8KVA4Aa"}
  - {"name":"20 https%3A%2F%2Ft.me%```2Filter_breaker","type":"ss","server":"79.127.200.169","port":990,"cipher":"chacha20-ietf-poly1305","password":"ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44="}
  - {"name":"21 https%3A%2F%2Ft.me%```2Filter_breaker","type":"ss","server":"185.176.221.72","port":24637,"cipher":"chacha20-ietf-poly1305","password":"MholStyHL7DhrewKbpQa20"}
  - {"name":"22 Filter_breaker","type":"ss","server":"156.146.38.170","port":443,"cipher":"aes-128-gcm","password":"shadowsocks"}
  - {"name":"23 @Config0plus کانال تلگرامی🚀`","type":"ss","server":"46.101.196.138","port":23243,"cipher":"chacha20-ietf-poly1305","password":"Q7cjiVD0oKNE2o9sUnZKQg"}
  - {"name":"24 https://t.me/PlanB_net","type":"trojan","server":"104.18.12.149","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"25 @Config0plus 🇳🇱 NL","type":"trojan","server":"172.64.149.54","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"26 Filter_breaker","type":"trojan","server":"188.114.96.3","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"27 کیانت`","type":"trojan","server":"8.6.112.6","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"28 @tel:@Config0plus`","type":"trojan","server":"8.6.112.0","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"29 Temp21@ZeusNet`","type":"trojan","server":"www.multiplydose.com","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"30 NormanV2ray-38","type":"trojan","server":"172.67.180.92","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"31 @unvisible_drops`","type":"trojan","server":"104.20.6.134","port":443,"password":"humanity","udp":true,"tls":true}
  - {"name":"32 @`irmeliy","type":"trojan","server":"sourceforge.net","port":443,"password":"humanity","udp":true,"tls":true}
proxy-groups:
  - name: "نوع انتخاب پروکسی 🔀"
    icon: https://www.svgrepo.com/show/412721/choose.svg
    type: select
    proxies:
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "بدون فیلترشکن 🛡️"
      - "قطع اینترنت ⛔"
  - name: "دستی 🤏🏻"
    type: select
    icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
    proxies:
      - "1 `@mtproto_proserver"
      - "2 `@mtproto_proserver"
      - "3 @mkill_network 🤍`"
      - "4 Telegram:++@Zero_Tunnel+7"
      - "5 Telegram : @Config0plus🥷🇧🇷`"
      - "6 @tik7net_vpn"
      - "7 تلگرام عضو شو @melibazz`"
      - "8 @ProtoRay"
      - "9 🕳️20@oneclickvpnkeys"
      - "10 🕳️5@oneclickvpnkeys"
      - "11 🚹60@oneclickvpnkeys`"
      - "12 🇬🇧4755 | ⚡️Telegram = t.me/LonUp_M"
      - "13 @v2rayconfigamir 2494"
      - "14 @aloconfig_com"
      - "15 برای اتصال دائمی جوین شو🗾 v2ray_configs_pools@"
      - "16 @internet_azad_2026`"
      - "17 T.me/MiTiVPN 4"
      - "18 melibaZz`"
      - "19 🕳️6@oneclickvpnkeys"
      - "20 https%3A%2F%2Ft.me%```2Filter_breaker"
      - "21 https%3A%2F%2Ft.me%```2Filter_breaker"
      - "22 Filter_breaker"
      - "23 @Config0plus کانال تلگرامی🚀`"
      - "24 https://t.me/PlanB_net"
      - "25 @Config0plus 🇳🇱 NL"
      - "26 Filter_breaker"
      - "27 کیانت`"
      - "28 @tel:@Config0plus`"
      - "29 Temp21@ZeusNet`"
      - "30 NormanV2ray-38"
      - "31 @unvisible_drops`"
      - "32 @`irmeliy"
  - name: "خودکار (بهترین پینگ) 🤖"
    type: url-test
    icon: https://www.svgrepo.com/show/7876/speedometer.svg
    url: https://api.v2fly.org/checkConnection.svgz
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "1 `@mtproto_proserver"
      - "2 `@mtproto_proserver"
      - "3 @mkill_network 🤍`"
      - "4 Telegram:++@Zero_Tunnel+7"
      - "5 Telegram : @Config0plus🥷🇧🇷`"
      - "6 @tik7net_vpn"
      - "7 تلگرام عضو شو @melibazz`"
      - "8 @ProtoRay"
      - "9 🕳️20@oneclickvpnkeys"
      - "10 🕳️5@oneclickvpnkeys"
      - "11 🚹60@oneclickvpnkeys`"
      - "12 🇬🇧4755 | ⚡️Telegram = t.me/LonUp_M"
      - "13 @v2rayconfigamir 2494"
      - "14 @aloconfig_com"
      - "15 برای اتصال دائمی جوین شو🗾 v2ray_configs_pools@"
      - "16 @internet_azad_2026`"
      - "17 T.me/MiTiVPN 4"
      - "18 melibaZz`"
      - "19 🕳️6@oneclickvpnkeys"
      - "20 https%3A%2F%2Ft.me%```2Filter_breaker"
      - "21 https%3A%2F%2Ft.me%```2Filter_breaker"
      - "22 Filter_breaker"
      - "23 @Config0plus کانال تلگرامی🚀`"
      - "24 https://t.me/PlanB_net"
      - "25 @Config0plus 🇳🇱 NL"
      - "26 Filter_breaker"
      - "27 کیانت`"
      - "28 @tel:@Config0plus`"
      - "29 Temp21@ZeusNet`"
      - "30 NormanV2ray-38"
      - "31 @unvisible_drops`"
      - "32 @`irmeliy"
  - name: سایتای ایرانی 🇮🇷
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
    proxies:
      - "بدون فیلترشکن 🛡️"
      - "نوع انتخاب پروکسی 🔀"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: تلگرام 💬
    type: select
    icon: https://www.svgrepo.com/show/354443/telegram.svg
    proxies:
      - "نوع انتخاب پروکسی 🔀"
      - "بدون فیلترشکن 🛡️"
      - "خودکار (بهترین پینگ) 🤖"
      - "دستی 🤏🏻"
      - "اجازه ندادن 🚫"
  - name: "بدون فیلترشکن 🛡️"
    type: select
    icon: https://www.svgrepo.com/show/6318/connection.svg
    proxies:
      - DIRECT
    hidden: true
  - name: "قطع اینترنت ⛔"
    type: select
    icon: https://www.svgrepo.com/show/305372/wifi-off.svg
    proxies:
      - REJECT
    hidden: true
  - name: "اجازه ندادن 🚫"
    type: select
    icon: https://www.svgrepo.com/show/444307/gui-ban.svg
    proxies:
      - REJECT
    hidden: true

rules:
  - RULE-SET,local_ips,بدون فیلترشکن 🛡️
  - PROCESS-NAME,Telegram.exe,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger,تلگرام 💬
  - PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
  - IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
  - RULE-SET,apps,سایتای ایرانی 🇮🇷
  - RULE-SET,iran,سایتای ایرانی 🇮🇷
  - RULE-SET,arvancloud,سایتای ایرانی 🇮🇷
  - RULE-SET,derakcloud,سایتای ایرانی 🇮🇷
  - RULE-SET,iranserver,سایتای ایرانی 🇮🇷
  - RULE-SET,parspack,سایتای ایرانی 🇮🇷
  - RULE-SET,irasn,سایتای ایرانی 🇮🇷
  - RULE-SET,ircidr,سایتای ایرانی 🇮🇷
  - RULE-SET,ir,سایتای ایرانی 🇮🇷
  - RULE-SET,category_ir,سایتای ایرانی 🇮🇷
  - MATCH,نوع انتخاب پروکسی 🔀

ntp:
  enable: true
  server: "time.apple.com"
  port: 123
  interval: 30
